import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runInNewContext } from 'node:vm';
import { bearerToken, randomSessionToken, secureEqual, sha256Hex, validPin } from '../server/ready/auth-core.mjs';
import { READY_RENDERERS, READY_TAXONOMY, validateQuestionSpec } from '../server/ready/question-spec.mjs';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const read=path=>readFileSync(resolve(root,path),'utf8');

assert.equal(validPin('1234'),true);
assert.equal(validPin('123456'),true);
assert.equal(validPin('123'),false);
const token=randomSessionToken();
assert.match(token,/^[A-Za-z0-9_-]{43}$/);
assert.equal(bearerToken(`Bearer ${token}`),token);
assert.equal((await sha256Hex(token)).length,64);
assert.equal(secureEqual('same-secret','same-secret'),true);
assert.deepEqual(READY_RENDERERS,['standard_mcq','annotated_passage_mcq','structural','summary','written_input']);
assert.ok(READY_TAXONOMY.includes('grammar_multi_error')&&READY_TAXONOMY.includes('summary_two_blank')&&READY_TAXONOMY.includes('guided_writing'));
const explicitSpec=validateQuestionSpec({taxonomy:'grammar_multi_error',import_status:'ready',spec:{renderer:'annotated_passage_mcq',passage:{source:'canonical',annotations:[{kind:'target',label:'ⓐ',text:'to reach'}]},choiceMode:'multi',responseMode:'choice',gradingMode:'exact_set'}},'multiple_choice','available');
assert.equal(explicitSpec.ready,true);
assert.equal(explicitSpec.spec.legacyAdapter,false);
assert.deepEqual(validateQuestionSpec({taxonomy:'sentence_insertion',import_status:'ready',stimulus:'Given.',spec:{renderer:'structural',passage:{source:'canonical'},extras:['stimulus'],choiceMode:'single',responseMode:'choice',gradingMode:'exact'}},'multiple_choice','available').spec.extras,['stimulus']);
assert.equal(validateQuestionSpec({taxonomy:'grammar_multi_error',import_status:'ready',spec:{renderer:'mystery'}},'multiple_choice','available').ready,false);

const baseline=read('supabase/migrations/20260826150000_ready_current_baseline.sql');
const questionMigration=read('supabase/migrations/20260828150000_ready_question_first.sql');
const neRelinkMigration=read('supabase/migrations/20260830130000_ready_relink_ne_textbook_aliases.sql');
const edge=read('server/ready/index.ts');
const app=read('ready/app.js');
const css=read('ready/ready.css');
const extractor=read('tools/ready-extract-ne-minbyeongcheon.py');
const busanExtractor=read('tools/ready-extract-busan-explanations.py');
const explanationMigration=read('supabase/migrations/20260830223000_ready_pdf_explanations.sql');
const workbookMigration=read('supabase/migrations/20260830234500_ready_workbook_attempts.sql');
const workbookExtractor=read('tools/ready-extract-ne-workbook.py');
const {NE_MINBYEONGCHEON_L1_WORKBOOK}=await import('../server/ready/workbook-ne-l1.mjs');

assert.match(baseline,/ready_questions[\s\S]*type text[\s\S]*payload jsonb/,'Question must remain generic JSON-backed data');
assert.match(baseline,/ready_attempts_are_immutable[\s\S]*before update or delete/,'Attempts must remain append-only');
assert.match(questionMigration,/ready_import_question_bundle[\s\S]*jsonb_array_elements[\s\S]*return imported/,'Atomic bundle import is missing');
assert.match(questionMigration,/multiple_choice[\s\S]*written_response/,'Both deterministic response types are not indexed/importable');
assert.match(questionMigration,/source_question_no[\s\S]*section/,'Source identity is not validated');
assert.match(explanationMigration,/ready_import_question_explanations[\s\S]*matched <> 1/,'PDF explanations are not imported by one exact Question identity');
assert.match(neRelinkMigration,/lesson\\s\*1[\s\S]*공통영어2[\s\S]*민병천[\s\S]*question_count desc/,'NE textbook aliases do not resolve to the question-bearing lesson');
assert.match(neRelinkMigration,/ready_exam_passages[\s\S]*surviving_passage_id[\s\S]*scope relink contract failed/,'NE scope relink is not atomic or verified');

assert.match(edge,/studentOps = new Set\(\["student_bootstrap", "student_passage", "student_questions", "student_review_questions", "submit_attempt", "student_workbook", "submit_workbook_attempt"\]\)/,'Student runtime exposes operations outside the Question and Workbook paths');
assert.doesNotMatch(edge.match(/async function dispatch[\s\S]*?\n\}/)?.[0]||'',/word_lookup|save_word|save_sentence|personal_library/,'Dormant lexical operations remain dispatched');
assert.match(edge,/function publicQuestion[\s\S]*responseSlots[\s\S]*variantSegments[\s\S]*contentBlocks/,'Structured public Question contract is incomplete');
assert.match(edge,/validateQuestionSpec[\s\S]*renderSpec[\s\S]*importStatus/,'Public Question does not expose its explicit render specification');
assert.match(edge,/isReadyQuestion[\s\S]*검수가 끝나지 않은 문제/,'Incomplete imports can reach students');
assert.doesNotMatch(edge.match(/function publicQuestion[\s\S]*?\n\}/)?.[0]||'',/accepted_answers|payload\.answer/,'Public Question exposes grading data');
assert.match(edge,/type === "multiple_choice"[\s\S]*selected\.length === answer\.length[\s\S]*selected\.every/,'MCQ grading is not deterministic set equality');
assert.match(edge,/type === "written_response"|question\.type === "written_response"/,'Written response grading is missing');
assert.match(edge,/normalize\("NFKC"\)[\s\S]*toLowerCase\(\)[\s\S]*replace\(\/\\s\+\/g/,'Written normalization is incomplete');
assert.match(edge,/accepted_response_sets[\s\S]*acceptedSets\.some/,'Linked written-response combinations are not graded atomically');
assert.match(edge,/inlineOptionGroups[\s\S]*inlineSelected[\s\S]*inlineAnswer/,'Inline passage-option grading is missing');
assert.match(edge,/detectedGroups[\s\S]*choicesMatchGroups\(detectedGroups, choices\)/,'Inline options can leak from a shared Passage into choices that do not encode those groups');
assert.match(edge,/\[ⓐ-ⓩ\]\|\\\(\[A-H\]\\\)/,'Parenthesized inline option groups are missing');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*123:[\s\S]*to hedge/,'Verified 23번 target repair is missing');
assert.match(edge,/\/요약\/\.test[\s\S]*sourceQuestionNo === 125 \? "vocabulary"/,'Summary prompts and 23번 vocabulary skill are not repaired');
assert.match(edge,/targetRanges[\s\S]*const interaction = "choices"/,'Passage metadata must point while MCQ answers stay in the plain choice list');
assert.match(edge,/choicesMatchGroups[\s\S]*inlineGroups[\s\S]*흐름상\|문맥상/,'Combination questions are not recognized from their own choices');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*97:[\s\S]*to take part[\s\S]*is related/,'18번 밑줄 범위 repair is missing');
assert.match(edge,/canonicalText:"related"[\s\S]*canonicalText:"interested"/,'Deliberately transformed targets do not retain their canonical anchors');
assert.match(edge,/SUMMARY_REPAIRS[\s\S]*101:[\s\S]*137:/,'Imported summary material is not repaired for existing rows');
assert.match(edge,/CHOICE_PART_REPAIRS[\s\S]*119:[\s\S]*122:/,'Multi-column source choices are not structurally repaired');
assert.match(edge,/CHOICE_PART_REPAIRS[\s\S]*19:[\s\S]*23:[\s\S]*28:[\s\S]*35:/,'Section 1 combination choices are still visually concatenated');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*118:[\s\S]*can define[\s\S]*the most[\s\S]*playing/,'22번 underline targets are not repaired');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*128:[\s\S]*to reach[\s\S]*familiar[\s\S]*were/,'24번 grammar targets do not point to complete expressions');
assert.match(edge,/WRITING_GUIDE_REPAIRS[\s\S]*277:[\s\S]*300:[\s\S]*343:[\s\S]*350:/,'18~28 written questions do not expose structured task guides');
for(const questionNo of [...Array.from({length:24},(_,index)=>277+index),...Array.from({length:8},(_,index)=>343+index)])assert.match(edge,new RegExp(`\\b${questionNo}:`),`Section 4 question ${questionNo} has no explicit UI contract`);
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*295:[\s\S]*that glows in the Orion constellation[\s\S]*297:/,'Written Passage focus ranges are incomplete');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*236:[\s\S]*bare imagination of a feast[\s\S]*240:[\s\S]*continued to explore/,'Meaning questions with label-only prompts lack their full source expressions');
assert.match(edge,/unresolvedQuestionIds[\s\S]*latest\.has[\s\S]*!correct/,'Review is not derived from the latest append-only Attempt');
assert.match(edge,/studentReviewQuestions[\s\S]*eligibleUnresolvedQuestionIds/,'Review queue endpoint is missing');
assert.match(edge,/isMainTextQuestion[\s\S]*isDialogueText[\s\S]*sourceBigrams/,'Textbook questions are not positively matched to the canonical main text');
assert.match(edge,/normalizeMainTextQuestionRows[\s\S]*Never infer its text[\s\S]*questionRows/,'Question text can still be inherited from an adjacent row');
assert.match(edge,/attemptedQuestionIds[\s\S]*!attempted\.has/,'Solved questions are not removed from the new-question queue');
assert.match(edge,/select\("id,passage_id,type,status,payload"\)[\s\S]*isReadyQuestion\(question\)/,'Home counts can include questions that have not passed spec review');
assert.match(edge,/cleanQuestionText[\s\S]*물음에\\s\*답하시오/,'Worksheet directions can still leak into the passage');
assert.match(edge,/setScopePassages[\s\S]*ready_relink_ne_minbyeongcheon_lessons[\s\S]*importQuestions[\s\S]*ready_relink_ne_minbyeongcheon_lessons/,'Scope changes and question imports do not repair textbook aliases');
assert.match(edge,/legacyWorkbook[\s\S]*publicStoredWritingGuide[\s\S]*CHOICE_PART_REPAIRS/,'Workbook-specific repairs are not scoped by source identity');
assert.match(edge,/setText: cleanQuestionText\(payload\.set_text[\s\S]*setId: clean\(payload\.source\.set_id/,'Question-set passage identity is not exposed to the student UI');

assert.match(app,/function renderReader[\s\S]*plainPassage/,'Reader does not render continuous prose');
assert.doesNotMatch(app,/openLexical|openSentence|translation_view|save_sentence|savedWord|savedSentence/,'Lexical/sentence study remains connected to the student frontend');
assert.match(app,/family\|\|'standard'[\s\S]*questionPassageHtml/,'Question family renderer is missing');
assert.match(app,/contentBlocks/,'Structured Passage blocks are not rendered');
assert.match(app,/questionBasePassage[\s\S]*summaryText/,'Question-local Passage variants and summary blocks are not rendered');
assert.match(app,/responseType==='written'[\s\S]*data-written-slot/,'Written response UI is missing');
assert.match(app,/writingGuideHtml[\s\S]*writing-conditions[\s\S]*writing-bank/,'Writing conditions and word bank are not separated from the prompt');
assert.match(app,/written-workspace correction[\s\S]*고친 말만 입력/,'Correction questions are not presented as expression-to-answer tasks');
assert.match(app,/sentence-answer[\s\S]*textarea[\s\S]*완성한 영어 문장/,'Sentence completion does not provide a usable writing area');
assert.match(app,/writtenSlotsHtml[\s\S]*multi-correction[\s\S]*summary-slots/,'Multi-slot summary and correction tasks are still flattened into one field');
assert.match(app,/writingGuide\?\.title\|\|question\.prompt/,'Flattened PDF prompts still override structured writing titles');
assert.doesNotMatch(app,/question-set-nav|questionSetKey|questionSetIndices|data-question-index/,'Questions are still bundled into a worksheet-set UI');
assert.match(app,/questionBasePassage\(question\)[\s\S]*question\.setText\|\|question\.variantText\|\|question\.passageText/,'A question does not prefer its own immutable worksheet context');
assert.match(app,/function questionBasePassage[\s\S]*function currentQuestionPassage[\s\S]*function questionPassageHtml/,'Current-question Passage composition is missing');
assert.match(app,/applyAlternativeOverlay[\s\S]*applyTargetOverlay[\s\S]*applyStructuralOverlay[\s\S]*pointedPassageHtml/,'Question overlays are not isolated by interaction type');
assert.match(app,/target\.canonicalText\|\|target\.text/,'Target overlays cannot distinguish source anchors from displayed expressions');
assert.match(app,/question\.skill==='implication'[\s\S]*question\.variantText[\s\S]*questionBasePassage\(question\)/,'Standalone implication and order questions do not use their explicit question material');
assert.match(app,/currentQuestionPassage\(question\)[\s\S]*questionPassageHtml\(question,result,selected\)/,'Question rendering still depends on adjacent questions');
assert.match(app,/canonicalOption[\s\S]*sort\(\(a,b\)=>b\.length-a\.length\)/,'Overlapping alternatives do not prefer the specific longer option');
assert.match(app,/passage-pointer[\s\S]*question-footnote/,'Plain Passage pointing and footnote rendering is missing');
assert.match(app,/markQuestionChoice[\s\S]*choiceSwipe[\s\S]*pointerdown[\s\S]*pointermove/,'Choice candidate swipe states are missing');
assert.match(app,/combinationChoiceParts[\s\S]*choice-separator/,'Grammar and vocabulary combination choices are not visually separated');
assert.match(edge,/inferredChoiceParts[\s\S]*row\.length === labels\.length/,'Unambiguous multi-blank choice columns are not preserved');
assert.match(app,/hasWorkbook[\s\S]*data-start-workbook/,'The interactive Lesson 1 Workbook is not reachable beside its Passage');
assert.doesNotMatch(app,/data-open-workbook|window\.open\([^)]*workbook/i,'Workbook still opens a passive PDF instead of an exercise');
assert.match(app,/student_workbook[\s\S]*submit_workbook_attempt[\s\S]*data-workbook-retry/,'Workbook input, grading, or retry flow is incomplete');
assert.match(app,/stage\.locked[\s\S]*준비 중[\s\S]*disabled/,'Workbook Stage 2 is not visibly locked');
assert.match(edge,/stage\.stage === 2[\s\S]*AI 채점 준비 중[\s\S]*item\.stage === 2/,'Workbook Stage 2 is not protected by the server');
assert.match(app,/workbookTaskHtml[\s\S]*choice_groups[\s\S]*correction_pairs[\s\S]*reorder_groups/,'Workbook exercise specs do not select the four deterministic UI primitives');
assert.match(app,/data-workbook-choice-group/,'Workbook inline choice interaction is missing');
assert.match(app,/data-workbook-order-remove[\s\S]*data-workbook-order-add/,'Workbook reorder interaction is missing');
assert.match(edge,/kind: item\.kind[\s\S]*hints:[\s\S]*groups:[\s\S]*pairCount:/,'Workbook public specs omit renderer fields');
assert.match(app,/explicitPassageHtml[\s\S]*renderSpec\.legacyAdapter[\s\S]*questionPassageHtml/,'Explicit Question specs do not drive whitelist rendering');
assert.match(app,/slotResults[\s\S]*틀린 부분 다시 풀기[\s\S]*event\.key!==['"]Enter['"]/,'Workbook does not identify the exact correction or support keyboard progression');
assert.match(edge,/slotResults = responses\.map[\s\S]*slotResults\.every\(Boolean\)[\s\S]*slotResults/,'Workbook grading does not report correctness per blank');
assert.match(workbookMigration,/create table if not exists public\.ready_workbook_attempts[\s\S]*ready_workbook_attempts_are_immutable[\s\S]*before update or delete/,'Workbook attempts must remain append-only');
assert.match(workbookExtractor,/STAGE_ANSWERS[\s\S]*for number in range\(1, 42\)[\s\S]*blank_count != len\(answers\)/,'Workbook extraction is not deterministically bounded');
assert.equal(NE_MINBYEONGCHEON_L1_WORKBOOK.stages.length,6,'Workbook must contain Stages 2, 3, 5, 6, 7, and 8');
const workbookItems=NE_MINBYEONGCHEON_L1_WORKBOOK.stages.flatMap(stage=>stage.items);
assert.equal(workbookItems.length,213,'Workbook must contain all deterministic Stage 2/3/5/6/7/8 items');
assert.equal(new Set(workbookItems.map(item=>item.key)).size,213,'Workbook item identities are not unique');
assert.deepEqual(Object.fromEntries(NE_MINBYEONGCHEON_L1_WORKBOOK.stages.map(stage=>[stage.stage,stage.items.length])),{2:41,3:41,5:41,6:41,7:8,8:41},'Workbook stage counts drifted from the PDF');
for(const item of workbookItems){
  assert.ok(['blank_input','verb_form','choice_groups','correction_pairs','reorder_groups'].includes(item.kind),`${item.key} has no supported exercise kind`);
  if(['blank_input','verb_form'].includes(item.kind))assert.equal((item.prompt.match(/_{5,}/g)||[]).length,item.answers.length,`${item.key} prompt/answer mismatch`);
  if(item.kind==='verb_form')assert.equal(item.hints.length,item.answers.length,`${item.key} hint/answer mismatch`);
  if(item.kind==='choice_groups'){assert.equal(item.groups.length,item.answers.length,`${item.key} choice/answer mismatch`);assert.equal((item.prompt.match(/⟦CHOICE:\d+⟧/g)||[]).length,item.answers.length,`${item.key} choice markers mismatch`);}
  if(item.kind==='correction_pairs')assert.equal(item.pairCount*2,item.answers.length,`${item.key} correction pair mismatch`);
  if(item.kind==='reorder_groups'){assert.equal(item.groups.length,item.answers.length,`${item.key} reorder/answer mismatch`);assert.equal((item.prompt.match(/⟦ORDER:\d+⟧/g)||[]).length,item.answers.length,`${item.key} reorder markers mismatch`);}
}
assert.match(app,/inactiveVariantText[\s\S]*question\.interaction!==['"]inline_options['"][\s\S]*canonicalHasOption/,'Inactive annotations are not cleaned from standalone questions');

const passageFunctionNames=['cleanDisplayText','referencedLabels','canonicalHasOption','canonicalOption','resolvedSetPassageText','labelNeedleIndex','replaceNeedle','maskBlank','worksheetPassageText','activeQuestionLabels','englishWordSpans','matchingTokenSequence','canonicalGap','restoreInactiveQuestionDevices','cleanQuestionApparatus','questionAnchorTexts','canonicalQuestionWindow','questionBasePassage','applyAlternativeOverlay','applyTargetOverlay','structuralMarkerPositions','applyStructuralOverlay','currentQuestionPassage'];
const passageFunctions=passageFunctionNames.map(name=>app.match(new RegExp(`function ${name}\\([^\\n]+`))?.[0]||'').join('\n');
const canonical18='Dear students, The annual Riverdale Science Fair will be held on July 18 with the theme Sustainable Future. Although we announced the fair last month, student registration is still lower than expected. Therefore, we would like to encourage more of you to take part. You are invited to present a project. You will have the opportunity to showcase your work. If you are interested, please submit a description. We look forward to your participation.';
const worksheet18='Dear students, The annual Riverdale Science Fair will ⓐ[hold / be held] on July 18 with the theme “㉠________.” (A) Although we announced the fair last month, student registration is still lower than expected. (B) You are ⓑ[inviting / invited] to present a project. (C) You will have the opportunity ⓒ[showcase / to showcase] your work. (D) If you are interested, please submit a description. (E) We look forward to your participation.';
const sharedSource={passageNo:18,section:'1',questionNo:1};
const setQuestions=[
  {skill:'grammar',passageText:canonical18,setText:worksheet18,inlineGroups:[{label:'ⓐ',options:['hold','be held']},{label:'ⓑ',options:['inviting','invited']},{label:'ⓒ',options:['showcase','to showcase']}],source:sharedSource},
  {skill:'blank',choices:['Space Tourism','Sustainable Future'],passageText:canonical18,setText:canonical18.replace('Sustainable Future','㉠______________________'),variantText:'㉠______________________',prompt:'빈칸 ㉠',source:sharedSource},
  {skill:'insertion',stimulus:'Therefore, we would like to encourage more of you to take part.',passageText:canonical18,variantText:'Opening. (A) First block. (B) Second block. (C) Third block. (D) Last block.',source:sharedSource},
  {skill:'content',passageText:canonical18,setText:canonical18,source:sharedSource},
];
const basePassages=setQuestions.map((question,index)=>runInNewContext(`${passageFunctions}; questionBasePassage(question)`,{question:{...question,id:`question-${index}`}}));
assert.match(basePassages[0],/ⓐbe held/,'The grammar question does not retain its own target before overlay composition');
assert.match(basePassages[1],/㉠_{4,}/,'The blank question does not preserve its own blank');
assert.doesNotMatch(basePassages[3],/[ⓐⓑⓒ]|㉠_{4,}/,'A content question inherits another question apparatus');
const overlayFor=index=>runInNewContext(`${passageFunctions}; currentQuestionPassage(question)`,{question:{...setQuestions[index],id:`question-${index}`}});
assert.match(overlayFor(0),/ⓐhold \/ be held[\s\S]*ⓑinviting \/ invited[\s\S]*ⓒshowcase \/ to showcase/,'Grammar alternatives are not presented without revealing the answer');
assert.match(overlayFor(1),/㉠_{4,}/,'The blank disappears when the current question is rendered');
assert.match(overlayFor(2),/\(A\)[\s\S]*\(B\)[\s\S]*\(C\)[\s\S]*\(D\)/,'Insertion positions are missing from the insertion question');
assert.doesNotMatch(overlayFor(3),/[ⓐⓑⓒ]|㉠_{4,}|\(A\)/,'A content question is contaminated by a neighbouring question');
assert.ok(new Set(setQuestions.map((_question,index)=>overlayFor(index))).size>1,'Independent questions still collapse to one shared worksheet variant');
const grammarTargets={skill:'grammar',prompt:'밑줄 친 ⓐ~ⓒ 중 어법상 어색한 것은?',passageText:'Light takes four years to reach us. It glows nearby and was familiar.',setText:'Light takes four years ⓐ to reach us. It ⓑglows nearby and ⓒ was familiar.',targetRanges:[{label:'ⓐ',text:'to reach'},{label:'ⓑ',text:'glows'},{label:'ⓒ',text:'was familiar'}],source:sharedSource};
assert.match(runInNewContext(`${passageFunctions}; currentQuestionPassage(question)`,{question:grammarTargets}),/ⓐto reach[\s\S]*ⓑglows[\s\S]*ⓒwas familiar/,'Grammar pointing does not cover each full target expression');
const targetCanonical='You are invited to present a model related to conservation. If you are interested, please submit it.';
const transformedTarget={skill:'grammar',passageText:targetCanonical,variantText:targetCanonical,targetRanges:[{label:'ⓒ',text:'is related',canonicalText:'related'},{label:'ⓓ',text:'interesting',canonicalText:'interested'}],source:sharedSource};
assert.match(runInNewContext(`${passageFunctions}; currentQuestionPassage(question)`,{question:transformedTarget}),/ⓒis related[\s\S]*ⓓinteresting/,'Variant-only target expressions cannot be anchored to canonical prose');
const implication={skill:'implication',passageText:'Canonical prose without a label.',variantText:'Context. (A)encourage more of you to take part. Ending.',source:{passageNo:18,section:'3',questionNo:233}};
assert.match(runInNewContext(`${passageFunctions}; currentQuestionPassage(question)`,{question:implication}),/\(A\)encourage more of you to take part/,'Implication question loses its explicit underlined expression');
const orderQuestion={skill:'order',prompt:'다음 글에 이어질 순서로 알맞은 것은?',choices:['(A)-(C)-(B)','(B)-(A)-(C)'],passageText:'Canonical prose.',variantText:'Opening. (A) First block. (B) Second block. (C) Third block.',source:{passageNo:18,section:'3',questionNo:255}};
assert.match(runInNewContext(`${passageFunctions}; currentQuestionPassage(question)`,{question:orderQuestion}),/\(A\)[\s\S]*\(B\)[\s\S]*\(C\)/,'Order question loses its explicit A/B/C blocks');
const authoredVariant={variantMode:'authored_variant',skill:'content',passageText:'Original canonical prose.',variantText:'The author deliberately paraphrased the original idea with different wording.',source:sharedSource};
assert.equal(runInNewContext(`${passageFunctions}; questionBasePassage(question)`,{question:authoredVariant}),authoredVariant.variantText,'An authored variant is incorrectly repaired back into canonical prose');
const cleanAuthoredVariant={variantMode:'authored_variant',skill:'content',prompt:'윗글의 내용과 일치하는 것은?',passageText:'The writer deliberately changed the opening. The closing sentence is original.',variantText:'The writer deliberately changed the opening. ⓐ[closing / opening] sentence is original.',source:sharedSource};
assert.equal(runInNewContext(`${passageFunctions}; questionBasePassage(question)`,{question:cleanAuthoredVariant}),'The writer deliberately changed the opening. closing sentence is original.','An authored variant keeps apparatus from another question');
const leeCanonical='Her dream was to attend Harvard Medical School, but at that time, the school did not accept women. She had no choice but to get married. It was not until she was in her fifties that Lee was able to start a career in medicine. He wanted to change the investigation system. She decided to devote the rest of her life to developing this field.';
const leeSet='Her dream was to attend Harvard Medical School, but at that time, the school did not accept women. ⓐ그녀는 결혼할 수밖에 없었다. It was not until she was in her fifties that Lee was able to start a career in medicine. He wanted to change the (A)____________ system. She decided to devote the rest of her life to (B)____________ this field.';
const leeBlank={skill:'blank',prompt:'윗글의 빈칸 (A), (B)에 들어갈 말은?',choices:['inquiry weakening','investigation developing'],passageText:leeCanonical,setText:leeSet,variantText:leeSet};
const leeWritten={skill:'written',prompt:'윗글의 밑줄 친 ⓐ의 우리말을 영작하시오.',choices:[],passageText:leeCanonical,setText:leeSet,variantText:leeSet,responseType:'written'};
const leeBlankText=runInNewContext(`${passageFunctions}; currentQuestionPassage(question)`,{question:leeBlank});
assert.doesNotMatch(leeBlankText,/[가-힣]/,'Inactive Korean translation leaks into an uppercase blank question');
assert.match(leeBlankText,/\(A\)_{3,}[\s\S]*\(B\)_{3,}/,'The current uppercase blanks disappear');
const leeWrittenText=runInNewContext(`${passageFunctions}; currentQuestionPassage(question)`,{question:leeWritten});
assert.match(leeWrittenText,/ⓐ그녀는 결혼할 수밖에 없었다/,'The current lowercase writing target disappears');
assert.doesNotMatch(leeWrittenText,/\(A\)|\(B\)|_{3,}/,'Inactive uppercase blanks leak into a writing question');
assert.match(leeWrittenText,/investigation system[\s\S]*developing this field/,'Inactive blanks are not restored from canonical prose');
assert.doesNotMatch(app.match(/function renderScope\(\)[\s\S]*?\n\}/)?.[0]||'',/data-open-review/,'Home still duplicates the top-level wrong-answer review route');
assert.match(app,/student_review_questions[\s\S]*복습 문제/,'Wrong-answer review UI is missing');
assert.match(app,/resultFeedbackHtml[\s\S]*data-toggle-explanation/,'Submitted answers cannot reveal an explanation progressively');
assert.doesNotMatch(app,/toggleExplanation[\s\S]{0,240}result\.correct/,'Correct answers are still blocked from revealing their explanation');
assert.match(edge,/return \{ attempt, correct, answer: correct \? null : answer, explanation \}/,'Correct attempts do not receive the verified explanation');
assert.match(extractor,/explanation_table[\s\S]*explanations\[number\]/,'Publisher explanations are not extracted into each Question payload');
assert.match(busanExtractor,/range\(1, 41\)[\s\S]*range\(97, 138\)[\s\S]*range\(211, 219\)[\s\S]*range\(343, 351\)/,'The 18-28 Busan explanation inventory is incomplete');
assert.match(busanExtractor,/for expected in range\(1, 365\)[\s\S]*len\(rows\) != 137/,'Busan explanations are not bounded by the complete PDF sequence and READY identity count');
assert.doesNotMatch(app,/data-toggle-answer|정답 보기|answer-reveal|showAnswer/,'A redundant answer-reveal control remains in the student UI');
assert.match(app,/readerParagraphs[\s\S]*study-back/,'Focused study navigation or paragraph Reader is missing');
assert.doesNotMatch(app,/function continuationQuestion|class="start-study"|class="home-tabs"/,'Home still exposes quick-start or study-mode tabs');
assert.match(app,/function exitQuestions[\s\S]*loadDashboard/,'Leaving a question session can show a stale Review count');
assert.match(css,/Question-first reset[\s\S]*reading-passage\{[\s\S]*display:block/,'Reader prose reset is missing');
assert.match(css,/question-block\.group[\s\S]*question-segment\.blank[\s\S]*written-response/,'Question family styling is incomplete');
assert.match(css,/written-workspace\.correction[\s\S]*writing-conditions[\s\S]*writing-bank/,'Structured writing workspace styling is incomplete');
assert.match(css,/correction-reference[\s\S]*written-slot-list/,'Complex correction and summary answers do not have readable field layouts');
assert.match(css,/@media\(max-width:700px\)[\s\S]*written-workspace\.correction\{grid-template-columns:1fr\}/,'Writing correction cards do not stack on mobile');
assert.match(css,/passage-pointer/,'Passage pointing styling is missing');
assert.doesNotMatch(css,/question-set-nav/,'Removed question-set navigation still has active styling');
assert.match(css,/passage-blank[\s\S]*white-space:nowrap/,'Inline blanks can still expand into an awkward wrapped bar');
assert.match(css,/question-choice\.eliminated[\s\S]*question-choice\.candidate/,'Choice deliberation states are missing');
assert.match(css,/font-size:16px!important/,'iOS Safari input zoom prevention is missing');
assert.match(css,/body\.study-mode #topbar\{display:none\}[\s\S]*\.study-back/,'Study mode still exposes the global top bar');
assert.match(extractor,/payload\["source_kind"\]\s*=\s*source_kind/,'Textbook import does not persist source boundaries');
for(const kind of ['textbook_main','dialogue','supplemental'])assert.match(extractor,new RegExp(`"${kind}"`),`Textbook source kind ${kind} is missing`);
assert.match(extractor,/current_context = source_before_conditions/,'A new written-response passage does not update the following shared context');
assert.match(css,/reader-shell>\.question-prompt\{[^}]*clamp\(18px,1\.65vw,22px\)/,'Question prompt has regressed to an oversized display heading');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/stimulus[\s\S]*target_ranges[\s\S]*city_tour_blocks/,'Question-set source repairs are missing from the importer');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/\("요약", "summary"\)[\s\S]*\("빈칸", "blank"\)/,'Summary questions are still misclassified as generic blanks');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/family == "summary"[\s\S]*summary_text/,'Summary material is not imported explicitly');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/TABLE_CHOICE_PARTS[\s\S]*119:[\s\S]*122:/,'Importer still flattens multi-column choices into ambiguous strings');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/TABLE_CHOICE_PARTS[\s\S]*19:[\s\S]*23:[\s\S]*28:[\s\S]*35:/,'Importer still flattens Section 1 grammar columns');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/question_no == 128[\s\S]*"text": "to reach"/,'Importer does not preserve the full 24번 grammar target');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/TARGET_RANGE_REPAIRS[\s\S]*102:[\s\S]*133:[\s\S]*240:/,'Importer lacks verified full-expression underline spans');

console.log('READY Question-first core checks passed');
