import { readyApi } from '../api.js';
import { UNGROUPED, addGroup, createScopeLayout, emptyGroupDefinitions, flattenScopeLayout, moveGroup, movePassage, passageIds, removeGroup, removePassage } from './scope-layout.js';
import { progressAccuracy } from './learning-progress.js';
import { questionAttemptReplayHtml, workbookAttemptReplayHtml } from './attempt-replay.js?v=admin-progress-1';

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const SESSION_KEY = 'ready-admin-session';
const state = { token:'', data:null, route:'students', passageEditorId:null, deleteTarget:null, passagePage:0, selectedPassageIds:new Set(), scopeEditor:null, factoryJob:null, factoryRows:[], learning:{period:'7d',school:'',grade:'',sort:'oldest',data:null,detail:null,replay:null} };
const SCOPE_SLOTS=[['중앙고','1학년'],['중앙고','2학년'],['동고','1학년'],['동고','2학년'],['신흥고','1학년'],['신흥고','2학년'],['한빛고','1학년'],['한빛고','2학년'],['test','1학년'],['test2','2학년']];
let busyCount = 0, toastTimer;
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
function setBusy(on, label='잠시만요…') { busyCount=Math.max(0,busyCount+(on?1:-1)); $('#busy').hidden=!busyCount; $('#busy span:last-child').textContent=label; }
function toast(message) { $('#toast').textContent=message; $('#toast').classList.add('on'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('on'),3200); }
function applyTheme(theme) { const dark=theme==='dark'; document.documentElement.classList.toggle('dark',dark); document.body.classList.toggle('dark',dark); localStorage.setItem('ready-theme',theme); }
function clearSession() { sessionStorage.removeItem(SESSION_KEY); state.token=''; state.data=null; }
async function call(op,data={},token=state.token,label='잠시만요…') { setBusy(true,label); try{return await readyApi(op,data,token);}finally{setBusy(false);} }
async function safely(job,{auth=true}={}) { try{return await job();}catch(error){if(auth&&error.status===401){clearSession();showLogin();}toast(error.message||'요청을 처리하지 못했습니다.');return null;} }
function showLogin() { $('#admin-login').hidden=false; $('#admin-nav').hidden=true; $('#admin-logout').hidden=true; $$('.view').forEach(view=>view.classList.remove('on')); }
function route(name) { state.route=name; $$('.view').forEach(view=>view.classList.toggle('on',view.id===`v-${name}`)); $$('.navbtn').forEach(button=>button.classList.toggle('on',button.dataset.route===(name==='scope-detail'?'scopes':name))); if(name==='scope-detail')renderScopeDetail();if(name==='progress'&&!state.learning.data)loadLearningProgress(); }
async function login(form) { const password=new FormData(form).get('password'); const data=await safely(()=>call('admin_login',{password},'','관리자 비밀번호를 확인하는 중…'),{auth:false}); form.reset(); if(!data)return; state.token=data.session.token; sessionStorage.setItem(SESSION_KEY,JSON.stringify(data.session)); await loadAdmin(); }
async function loadAdmin() { const data=await safely(()=>call('teacher_bootstrap',{},state.token,'관리자 화면을 불러오는 중…')); if(!data)return; state.data=data; $('#admin-login').hidden=true; $('#admin-nav').hidden=false; $('#admin-logout').hidden=false; renderStudents(); renderPassages(); renderScopes(); renderFactoryPassageOptions(); syncLearningFilterOptions(); route(state.route); }
async function logout() { if(state.token)await safely(()=>call('logout')); clearSession(); showLogin(); }
async function importQuestionBundle(form) {
  const file=new FormData(form).get('bundle');
  if(!(file instanceof File)||!file.size)return toast('가져올 JSON 파일을 선택해 주세요.');
  let bundle;
  try{bundle=JSON.parse(await file.text());}catch{return toast('올바른 JSON 문제 번들이 아닙니다.');}
  const questions=Array.isArray(bundle)?bundle:bundle?.questions;
  if(!Array.isArray(questions)||!questions.length)return toast('가져올 READY 문항이 없습니다.');
  if(questions.some(question=>question?.status!=='available'||question?.payload?.import_status!=='ready'))return toast('READY가 아닌 문항이 포함되어 가져오기를 중단했습니다.');
  const data=await safely(()=>call('import_questions',{questions},state.token,`${questions.length}개 READY 문항을 가져오는 중…`));
  if(!data)return;
  form.reset();await loadAdmin();route('passages');toast(`${data.imported||questions.length}개 READY 문항을 가져왔습니다.`);
}
function renderFactoryPassageOptions(){const select=$('#factory-existing-passage');if(!select||!state.data)return;const current=select.value;select.innerHTML=`<option value="">Passage를 선택하세요</option>${state.data.passages.map(passage=>`<option value="${passage.id}" ${passage.has_workbook?'disabled':''}>${escapeHtml([passage.source_year,passage.source_month&&passage.source_month+'월',passage.title,passage.has_workbook&&`워크북 있음 (${passage.workbook_source})`].filter(Boolean).join(' · '))}</option>`).join('')}`;if([...select.options].some(option=>option.value===current&&!option.disabled))select.value=current;syncFactoryMode();}
function syncFactoryMode(){const form=$('#factory-start-form');if(!form)return;const existing=form.elements.factoryMode.value==='existing_passage',existingField=$('#factory-existing-field'),newFields=$('#factory-new-fields'),title=form.elements.title,passage=form.elements.existingPassageId;existingField.hidden=!existing;newFields.hidden=existing;title.required=!existing;passage.required=existing;$('#factory-pdf-note').textContent=existing?'선택 사항 · exercise/Answer Key 추출과 canonical 일치 검사에만 사용합니다.':'또는 아래에 본문을 붙여 넣으세요.';form.elements.sourceText.closest('label').hidden=existing;}
function factoryCoverage(metrics){return [1,2,3,4,5,6,7].map(stage=>{const value=metrics?.stageCoverage?.[stage]||{};return `${stage}단계 ${Number(value.ready)||0}/${Number(value.expected)||0}`;}).join(' · ');}
function renderFactoryReview(result){const root=$('#factory-review');if(!root)return;const job=result?.job||state.factoryJob;if(!job)return;const changedJob=state.factoryJob?.id!==job.id;state.factoryJob=job;if(changedJob||!state.factoryRows.length)state.factoryRows=Array.isArray(job.extracted_rows)?job.extracted_rows.map(row=>({text:String(row.text||''),translation:String(row.translation||'')})):[];const extraction=job.extraction||{},existing=job.source_metadata?.factoryMode==='existing_passage';root.hidden=false;root.innerHTML=`<section class="card form-card"><p class="eyebrow">${existing?'CANONICAL CHECK':'SENTENCE REVIEW'}</p><h2>${existing?'기존 Passage 문장 확인':'문장쌍 확정'}</h2><p class="lead">${escapeHtml(extraction.reason||'영문/한글 문장쌍을 확인해 주세요.')} ${existing?'이 문장들은 수정되지 않습니다.':'현재 순서가 문장 번호입니다.'}</p><div class="table-wrap"><table><thead><tr><th>#</th><th>English</th><th>해석</th>${existing?'':'<th></th>'}</tr></thead><tbody>${state.factoryRows.map((row,index)=>`<tr><td>${index+1}</td><td><textarea data-factory-en="${index}" rows="3" ${existing?'readonly':''}>${escapeHtml(row.text)}</textarea></td><td><textarea data-factory-ko="${index}" rows="3" ${existing?'readonly':''}>${escapeHtml(row.translation)}</textarea></td>${existing?'':`<td><button class="button danger small" type="button" data-factory-delete="${index}">삭제</button><button class="button quiet small" type="button" data-factory-add-after="${index}">+ 아래</button></td>`}</tr>`).join('')}</tbody></table></div>${existing?'':'<button class="button quiet" type="button" data-factory-add-after="'+(state.factoryRows.length-1)+'">+ 문장 추가</button>'}<button class="button primary" type="button" data-factory-confirm>${existing?'워크북 검증':'문장 확인 및 워크북 검증'}</button></section>`;}
function captureFactoryRows(){if(state.factoryJob?.source_metadata?.factoryMode==='existing_passage')return;state.factoryRows=state.factoryRows.map((row,index)=>({text:document.querySelector(`[data-factory-en="${index}"]`)?.value?.trim()||row.text,translation:document.querySelector(`[data-factory-ko="${index}"]`)?.value?.trim()||row.translation}));}
function selectedFactoryPdf(form,data){const input=form.querySelector('input[type="file"][accept*="pdf"]'),direct=input?.files?.[0],fallback=data.get('pdf'),file=direct||fallback;return file&&typeof file==='object'&&Number(file.size)>0?file:null;}
async function startFactory(form){const data=new FormData(form),values=Object.fromEntries(data),existing=values.factoryMode==='existing_passage',pdf=selectedFactoryPdf(form,data),sourceText=String(data.get('sourceText')||'').trim();delete values.pdf;if(existing&&!values.existingPassageId)return toast('기존 Passage를 선택해 주세요.');if(!pdf){if(!existing&&!sourceText)return toast('PDF 또는 본문을 입력해 주세요.');const result=await safely(()=>call('factory_start',{...values,sourceKind:'text',sourceText},state.token,existing?'기존 Passage를 확인하는 중…':'본문을 분석하는 중…'));if(result)renderFactoryReview(result);return;}if(pdf.size>7_000_000)return toast('PDF는 7MB 이하로 올려 주세요.');const pdfBase64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('PDF를 읽을 수 없습니다.'));reader.onload=()=>resolve(String(reader.result||''));reader.readAsDataURL(pdf);});const result=await safely(()=>call('factory_start',{...values,sourceKind:'pdf',pdfBase64,documentName:pdf.name},state.token,'PDF를 분석하는 중…'));if(result)renderFactoryReview(result);}
async function confirmFactory({finalize=false,allowIncomplete=false}={}){if(!state.factoryJob)return;const existing=state.factoryJob.source_metadata?.factoryMode==='existing_passage';if(!finalize)captureFactoryRows();const payload={jobId:state.factoryJob.id,finalize,allowIncomplete,...(!finalize&&!existing?{sentenceRows:state.factoryRows}:{})};const result=await safely(()=>call('factory_confirm',payload,state.token,finalize?'Passage와 워크북을 최종 저장하는 중…':'워크북을 생성하고 검증하는 중…'));if(!result)return;if(finalize&&result.incompleteReview){$('#factory-review').innerHTML=`<section class="card form-card"><div class="result bad"><strong>최종 저장 전 검증 결과가 달라졌습니다.</strong><p>${escapeHtml(factoryCoverage(result.metrics))}</p><p>Passage와 워크북은 아직 저장되지 않았습니다. 누락을 인정하고 저장하려면 아래 버튼을 눌러 주세요.</p></div><button class="button danger" type="button" data-factory-finalize-incomplete>누락을 인정하고 최종 확정</button></section>`;return;}if(!finalize&&result.confirmationRequired){const incomplete=result.incompleteReview===true;$('#factory-review').innerHTML=`<section class="card form-card"><div class="result ${incomplete?'bad':'good'}"><strong>${incomplete?'단계별 문제 수를 확인해 주세요.':'검증 완료'}</strong><p>${escapeHtml(factoryCoverage(result.metrics))}</p><p>${incomplete?'누락된 exercise는 학생에게 공개되지 않습니다. 아래 버튼을 누르면 이 상태를 인정하고 Passage와 워크북을 저장합니다.':'모든 필수 단계가 검증되었습니다. 아래 버튼을 눌러야 Passage와 워크북이 실제로 저장됩니다.'}</p></div><button class="button ${incomplete?'danger':'primary'}" type="button" ${incomplete?'data-factory-finalize-incomplete':'data-factory-finalize'}>${incomplete?'누락을 인정하고 최종 확정':'최종 확정'}</button></section>`;return;}state.factoryJob={...state.factoryJob,status:'ready'};$('#factory-review').innerHTML=`<div class="card result good"><strong>Workbook ready</strong><p>${escapeHtml(factoryCoverage(result.metrics))}</p><p>문장 ${result.metrics?.sentenceCount||0} · deterministic ${result.metrics?.deterministicGeneratedExercises||0} · Gemini ${result.metrics?.geminiGeneratedExercises||0} · validator DROP ${result.metrics?.validatorDrop||0}</p></div>`;await loadAdmin();toast(existing?'기존 Passage는 그대로 두고 워크북만 저장했습니다.':'최종 확정되어 Passage와 READY 워크북을 저장했습니다.');}
async function regenerateFactoryWorkbook(passageId){const passage=state.data?.passages.find(item=>item.id===passageId);if(!passage||passage.workbook_source!=='factory')return;if(!confirm(`“${passage.title}” 워크북을 최신 Factory 규칙으로 다시 생성할까요?\n기존 Passage와 Questions는 변경되지 않습니다.`))return;const result=await safely(()=>call('factory_regenerate',{passageId},state.token,'기존 워크북을 최신 규칙으로 재생성하는 중…'));if(!result)return;if(result.incompleteReview){toast(`재생성 중단 · ${factoryCoverage(result.metrics)}`);return;}await loadAdmin();toast(`워크북 재생성 완료 · ${factoryCoverage(result.metrics)}`);}
function passagesForExam(examId){const byId=new Map(state.data.passages.map(passage=>[passage.id,passage]));return state.data.examPassages.filter(link=>link.exam_id===examId).sort((a,b)=>a.position-b.position).map(link=>{const passage=byId.get(link.passage_id);return passage?{...passage,scope_position:link.position,group_key:link.group_key,group_label:link.group_label}:null;}).filter(Boolean);}

function syncLearningFilterOptions(){if(!state.data)return;const schools=[...new Set(state.data.students.map(student=>student.school))].sort((a,b)=>a.localeCompare(b,'ko')),grades=[...new Set(state.data.students.map(student=>student.grade))].sort((a,b)=>a.localeCompare(b,'ko'));const school=$('#learning-school-filter'),grade=$('#learning-grade-filter');if(school)school.innerHTML=`<option value="">전체 학교</option>${schools.map(value=>`<option ${state.learning.school===value?'selected':''}>${escapeHtml(value)}</option>`).join('')}`;if(grade)grade.innerHTML=`<option value="">전체 학년</option>${grades.map(value=>`<option ${state.learning.grade===value?'selected':''}>${escapeHtml(value)}</option>`).join('')}`;}
function relativeActivity(value){if(!value)return'학습 기록 없음';const elapsed=Math.max(0,Date.now()-Date.parse(value)),minute=60_000,hour=60*minute,day=24*hour;if(elapsed<minute)return'방금';if(elapsed<hour)return`${Math.floor(elapsed/minute)}분 전`;if(elapsed<day)return`${Math.floor(elapsed/hour)}시간 전`;if(elapsed<2*day)return'어제';return`${Math.floor(elapsed/day)}일 전`;}
function accuracyHtml(metrics){const accuracy=progressAccuracy(metrics?.correct,metrics?.total);return accuracy==null?'—':`${accuracy}%`;}
async function loadLearningProgress(){const learning=state.learning,data=await safely(()=>call('admin_learning_progress',{period:learning.period,school:learning.school,grade:learning.grade},state.token,'학습 현황을 계산하는 중…'));if(!data)return;learning.data=data;learning.detail=null;learning.replay=null;renderLearningProgress();}
function renderLearningProgress(){const root=$('#learning-progress-summary'),detail=$('#learning-progress-detail');if(!root||!state.learning.data)return;if(detail)detail.hidden=true;root.hidden=false;const learning=state.learning,rows=[...(learning.data.students||[])].sort((a,b)=>{const left=a.lastActivityAt?Date.parse(a.lastActivityAt):0,right=b.lastActivityAt?Date.parse(b.lastActivityAt):0;return learning.sort==='recent'?right-left:left-right;});$$('[data-learning-period]').forEach(button=>button.classList.toggle('active',button.dataset.learningPeriod===learning.period));const sort=$('#learning-sort');if(sort)sort.value=learning.sort;root.innerHTML=rows.length?`<div class="table-wrap learning-table"><table><thead><tr><th>학생</th><th>마지막 학습</th><th>문제</th><th>문제 정답률</th><th>문제 오답</th><th>워크북</th><th>워크북 정답률</th><th>워크북 오답</th></tr></thead><tbody>${rows.map(student=>`<tr tabindex="0" role="button" data-open-learning-student="${student.id}" aria-label="${escapeHtml(student.name)} 학습 상세"><td><strong>${escapeHtml(student.name)}</strong><small>${escapeHtml(student.school)} · ${escapeHtml(student.grade)}</small></td><td>${escapeHtml(relativeActivity(student.lastActivityAt))}</td><td>${student.question.total}</td><td>${accuracyHtml(student.question)}</td><td>${student.question.wrong}</td><td>${student.workbook.total}</td><td>${accuracyHtml(student.workbook)}</td><td>${student.workbook.wrong}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">조건에 맞는 학생이 없습니다.</div>';}
function attemptWhen(value){return new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Seoul'}).format(new Date(value));}
function questionGroupHtml(items){const byQuestion=new Map();for(const item of items){const list=byQuestion.get(item.questionId)||[];list.push(item);byQuestion.set(item.questionId,list);}return [...byQuestion.values()].map((attempts,index)=>{const item=attempts[0],difficulty={1:'쉬움',2:'보통',3:'어려움'}[item.difficulty]||'난이도 없음';return `<details class="learning-wrong-group" ${index===0?'open':''}><summary><span><strong>${escapeHtml(item.passageTitle)}</strong><small>${escapeHtml(item.taxonomyLabel||item.taxonomy||'Question')} · ${difficulty}${item.referenceQuestionNo?` · Ref ${item.referenceQuestionNo}`:''}</small></span><b>${item.attemptCount}회 시도 / ${item.wrongCount}회 오답</b></summary><div>${attempts.map((attempt,attemptIndex)=>`<button type="button" data-open-learning-attempt="${attempt.id}" data-learning-attempt-kind="question"><span>오답 시도 ${attemptIndex+1}</span><small>${escapeHtml(attemptWhen(attempt.createdAt))}</small><b>보기 →</b></button>`).join('')}</div></details>`;}).join('');}
function workbookGroupHtml(items){const byItem=new Map();for(const item of items){const key=`${item.passageTitle}:${item.stage}:${item.itemKey}`,list=byItem.get(key)||[];list.push(item);byItem.set(key,list);}return [...byItem.values()].map((attempts,index)=>{const item=attempts[0];return `<details class="learning-wrong-group" ${index===0?'open':''}><summary><span><strong>${escapeHtml(item.passageTitle)}</strong><small>Stage ${item.stage}${item.kind?` · ${escapeHtml(item.kind)}`:''}${item.number?` · ${escapeHtml(item.number)}`:''}</small></span><b>${item.attemptCount}회 시도 / ${item.wrongCount}회 오답</b></summary><div>${attempts.map((attempt,attemptIndex)=>`<button type="button" data-open-learning-attempt="${attempt.id}" data-learning-attempt-kind="workbook"><span>오답 시도 ${attemptIndex+1}</span><small>${escapeHtml(attemptWhen(attempt.createdAt))}${attempt.replayAvailable?'':' · 현재 catalog 불일치'}</small><b>보기 →</b></button>`).join('')}</div></details>`;}).join('');}
async function openLearningStudent(studentId){const data=await safely(()=>call('admin_learning_progress_detail',{studentId,period:state.learning.period},state.token,'학생 학습 기록을 불러오는 중…'));if(!data)return;state.learning.detail=data;state.learning.replay=null;renderLearningDetail();}
function renderLearningDetail(){const data=state.learning.detail,summary=$('#learning-progress-summary'),root=$('#learning-progress-detail');if(!data||!root)return;summary.hidden=true;root.hidden=false;root.innerHTML=`<div class="learning-detail-head"><button class="back-link" type="button" data-close-learning-student>← 학생별 현황</button><div><p class="eyebrow">STUDENT · ${escapeHtml(state.learning.period==='today'?'오늘':state.learning.period==='30d'?'최근 30일':'최근 7일')}</p><h1>${escapeHtml(data.student.name)}</h1><p>${escapeHtml(data.student.school)} · ${escapeHtml(data.student.grade)}</p></div><div class="learning-detail-metrics"><span><strong>Question ${data.question.total}개</strong>${accuracyHtml(data.question)}</span><span><strong>Workbook ${data.workbook.total}개</strong>${accuracyHtml(data.workbook)}</span><span><strong>마지막 학습</strong>${escapeHtml(relativeActivity(state.learning.data?.students?.find(student=>student.id===data.student.id)?.lastActivityAt))}</span></div></div><div id="learning-attempt-replay" hidden></div>${!data.question.total&&!data.workbook.total?'<div class="empty learning-empty">선택한 기간에 학습 기록이 없습니다.</div>':`<div class="learning-wrong-layout"><section><header><h2>틀린 문제</h2><small>오답 attempt ${data.wrongQuestions.length}회</small></header>${data.wrongQuestions.length?questionGroupHtml(data.wrongQuestions):'<div class="empty compact-empty">틀린 문제가 없습니다.</div>'}</section><section><header><h2>틀린 Workbook</h2><small>오답 attempt ${data.wrongWorkbooks.length}회</small></header>${data.wrongWorkbooks.length?workbookGroupHtml(data.wrongWorkbooks):'<div class="empty compact-empty">틀린 Workbook이 없습니다.</div>'}</section></div>`}`;}
async function openLearningAttempt(attemptId,kind){const data=await safely(()=>call('admin_attempt_replay',{attemptId,kind},state.token,'제출 화면을 재현하는 중…'));if(!data)return;state.learning.replay=data;const root=$('#learning-attempt-replay');if(!root)return;root.hidden=false;root.innerHTML=`<div class="learning-replay-toolbar"><button class="back-link" type="button" data-close-learning-attempt>← 오답 목록</button><span>${escapeHtml(attemptWhen(data.attempt?.created_at))}</span></div>${kind==='question'?questionAttemptReplayHtml(data,escapeHtml):workbookAttemptReplayHtml(data,escapeHtml)}`;root.scrollIntoView({behavior:'smooth',block:'start'});}

function renderStudents() {
  const school=$('#student-school-filter')?.value||'',grade=$('#student-grade-filter')?.value||'';
  const students=state.data.students.filter(student=>(!school||student.school===school)&&(!grade||student.grade===grade));
  const root=$('#admin-students');
  root.innerHTML=students.length?`<div class="table-wrap student-table"><table><thead><tr><th>이름</th><th>학교 / 학년</th><th>학생 코드 변경</th><th></th></tr></thead><tbody>${students.map(student=>`<tr><td><strong>${escapeHtml(student.name)}</strong></td><td>${escapeHtml(student.school)} · ${escapeHtml(student.grade)}</td><td><form class="pin-reset" data-reset-code="${student.id}"><input name="code" type="password" inputmode="numeric" pattern="[0-9]{6}" minlength="6" maxlength="6" autocomplete="new-password" placeholder="새 6자리 코드" required><button class="button quiet small" type="submit">변경</button></form></td><td><button class="button danger small" type="button" data-delete-student="${student.id}">삭제</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">조건에 맞는 학생이 없습니다.</div>';
}
function renderPassageSelection(){
  const root=$('#passage-selection'), selected=state.data.passages.filter(p=>state.selectedPassageIds.has(p.id)); if(!root)return;
  if(!selected.length){root.innerHTML='';return;}
  const grades=[...new Set(selected.map(p=>p.grade))], mixed=grades.length!==1;
  root.innerHTML=`<section class="card passage-selection"><div class="selection-summary"><strong>${selected.length}개 지문 선택</strong><button class="button quiet small" type="button" data-clear-passage-selection>선택 해제</button></div>${mixed?'<div class="result bad">같은 학년 지문만 하나의 시험범위에 배정할 수 있습니다.</div>':`<form id="assign-passages-to-scope" class="form-grid scope-assign"><label><span>학교</span><select name="school" required>${SCOPE_SLOTS.filter(([,grade])=>grade===grades[0]).map(([school])=>`<option>${school}</option>`).join('')}</select></label><label><span>학년</span><input name="grade" value="${escapeHtml(grades[0])}" readonly></label><button class="button primary" type="submit">선택한 지문 배정</button></form>`}</section>`;
}
function renderPassages(){const root=$('#passage-library');if(!root)return;const validIds=new Set(state.data.passages.map(p=>p.id));state.selectedPassageIds=new Set([...state.selectedPassageIds].filter(id=>validIds.has(id)));const grade=$('#passage-grade-filter')?.value||'',type=$('#passage-type-filter')?.value||'',year=$('#passage-year-filter')?.value||'',month=$('#passage-month-filter')?.value||'';const rows=state.data.passages.filter(p=>(!grade||p.grade===grade)&&(!type||p.source_type===type)&&(!year||String(p.source_year)===year)&&(!month||String(p.source_month)===month));const pageSize=15,totalPages=Math.max(1,Math.ceil(rows.length/pageSize));state.passagePage=Math.min(state.passagePage,totalPages-1);const page=rows.slice(state.passagePage*pageSize,(state.passagePage+1)*pageSize);root.innerHTML=`<div class="library-note"><span>지문을 체크해 시험범위에 배정하세요.</span></div><div class="table-wrap"><table><thead><tr><th>선택</th><th>제목</th><th>종류</th><th>학년</th><th>출처</th><th></th></tr></thead><tbody>${page.map(p=>`<tr data-passage-row="${p.id}"><td><input class="passage-check" type="checkbox" aria-label="${escapeHtml(p.title)} 선택" data-select-passage="${p.id}" ${state.selectedPassageIds.has(p.id)?'checked':''}></td><td><button class="text-button" type="button" data-edit-passage="${p.id}">${escapeHtml(p.title)}</button></td><td>${p.source_type==='MOCK_EXAM'?'모의고사':'교과서'}</td><td>${escapeHtml(p.grade)}</td><td>${escapeHtml([p.source_year,p.source_month&&p.source_month+'월',p.source_label].filter(Boolean).join(' · ')||'—')}</td><td>${p.workbook_source==='factory'?`<button class="button quiet small" type="button" data-regenerate-workbook="${p.id}">워크북 재생성</button>`:''}<button class="button quiet small" type="button" data-edit-passage="${p.id}">수정</button><button class="button danger small" type="button" data-delete-passage="${p.id}">삭제</button></td></tr>`).join('')||'<tr><td colspan="6">조건에 맞는 지문이 없습니다.</td></tr>'}</tbody></table></div><div class="pagination"><button class="button quiet small" type="button" data-passage-page="prev" ${state.passagePage===0?'disabled':''}>← Prev</button><span>${state.passagePage+1} / ${totalPages}</span><button class="button quiet small" type="button" data-passage-page="next" ${state.passagePage===totalPages-1?'disabled':''}>Next →</button></div>`;renderPassageSelection();}
function openPassage(passageId){const passage=state.data.passages.find(item=>item.id===passageId);if(!passage)return;state.passageEditorId=passageId;$('#passage-editor').innerHTML=`<form id="update-passage-form"><div class="form-grid"><label><span>제목</span><input name="title" value="${escapeHtml(passage.title)}" required></label><label><span>종류</span><select name="sourceType"><option value="TEXTBOOK" ${passage.source_type==='TEXTBOOK'?'selected':''}>교과서</option><option value="MOCK_EXAM" ${passage.source_type==='MOCK_EXAM'?'selected':''}>모의고사</option></select></label><label><span>학년</span><select name="grade">${['1학년','2학년','3학년'].map(value=>`<option ${passage.grade===value?'selected':''}>${value}</option>`).join('')}</select></label><label><span>연도</span><input name="sourceYear" value="${passage.source_year||''}"></label><label><span>월</span><input name="sourceMonth" value="${passage.source_month||''}"></label></div><p class="lead compact">문장과 해석은 등록 시 확정한 행을 그대로 사용합니다.</p><button class="button primary" type="submit">지문 정보 저장</button></form>`;$('#passage-modal').classList.add('on');$('#passage-modal').setAttribute('aria-hidden','false');}
function closePassage(){$('#passage-modal').classList.remove('on');$('#passage-modal').setAttribute('aria-hidden','true');state.passageEditorId=null;}
function renderScopes() {
  const root=$('#teacher-exams');
  const schools=[...new Set(SCOPE_SLOTS.map(([school])=>school))];
  root.innerHTML=schools.map(school=>`<section class="scope-school"><h2>${escapeHtml(school)}${school.startsWith('test')?' · QA 전용':''}</h2><div class="scope-grid">${SCOPE_SLOTS.filter(([slotSchool])=>slotSchool===school).map(([,grade])=>{const scope=state.data.exams.find(item=>item.school===school&&item.grade===grade),passages=scope?passagesForExam(scope.id):[];return `<button class="card scope-card scope-card-button" type="button" data-open-scope-school="${escapeHtml(school)}" data-open-scope-grade="${escapeHtml(grade)}"><div class="card-head"><div><p class="eyebrow">${school.startsWith('test')?'PRIVATE QA SCOPE':'CURRENT SCOPE'}</p><h3>${escapeHtml(grade)}</h3><p class="lead compact">지문 ${passages.length}개</p></div><span class="scope-card-arrow" aria-hidden="true">→</span></div><div class="passage-list">${passages.slice(0,4).map((p,index)=>`<div class="recent-row"><span>${index+1}. ${escapeHtml(p.title)}</span></div>`).join('')||'<div class="empty compact-empty">아직 배정된 지문이 없습니다.</div>'}${passages.length>4?`<p class="lead compact">외 ${passages.length-4}개</p>`:''}</div><span class="scope-card-cta">눌러서 묶음·순서 편집</span></button>`;}).join('')}</div></section>`).join('');
}
function scopePassageRow(passageId,groupKey,index){const passage=state.data.passages.find(item=>item.id===passageId);if(!passage)return'';const options=[['','묶음 없음'],...state.scopeEditor.layout.groups.map(group=>[group.key,group.label])],list=groupKey?state.scopeEditor.layout.groups.find(group=>group.key===groupKey)?.passageIds:state.scopeEditor.layout.ungrouped;return `<div class="scope-layout-passage" draggable="true" data-scope-passage="${passage.id}" data-scope-group="${escapeHtml(groupKey)}"><span class="drag-handle" aria-hidden="true">≡</span><span class="scope-layout-passage-copy"><strong>${escapeHtml(passage.title)}</strong><small>${passage.source_type==='MOCK_EXAM'?'모의고사':'교과서'} · ${escapeHtml(passage.source_label||passage.grade)}</small></span><select data-move-scope-passage="${passage.id}" aria-label="${escapeHtml(passage.title)} 묶음 이동">${options.map(([key,label])=>`<option value="${escapeHtml(key)}" ${key===groupKey?'selected':''}>${escapeHtml(label)}</option>`).join('')}</select><span class="scope-order-buttons"><button type="button" class="icon-button" data-move-passage-up="${passage.id}" aria-label="위로 이동" ${index===0?'disabled':''}>↑</button><button type="button" class="icon-button" data-move-passage-down="${passage.id}" aria-label="아래로 이동" ${index===list.length-1?'disabled':''}>↓</button></span></div>`;}
function scopeGroup(group,index){const collapsed=state.scopeEditor.collapsedGroups?.has(group.key);return `<section class="scope-layout-group ${collapsed?'is-collapsed':''}" draggable="true" data-scope-group-card="${escapeHtml(group.key)}"><header><span class="drag-handle" aria-hidden="true">≡</span><input value="${escapeHtml(group.label)}" maxlength="120" aria-label="묶음 이름" data-scope-group-label="${escapeHtml(group.key)}" required><button type="button" class="button quiet small scope-collapse" data-toggle-scope-group="${escapeHtml(group.key)}" aria-expanded="${collapsed?'false':'true'}">${collapsed?'펼치기':'접기'}</button><span class="scope-order-buttons"><button type="button" class="icon-button" data-move-group-up="${escapeHtml(group.key)}" aria-label="묶음 위로 이동" ${index===0?'disabled':''}>↑</button><button type="button" class="icon-button" data-move-group-down="${escapeHtml(group.key)}" aria-label="묶음 아래로 이동" ${index===state.scopeEditor.layout.groups.length-1?'disabled':''}>↓</button></span><button type="button" class="button danger small" data-delete-scope-group="${escapeHtml(group.key)}">묶음 삭제</button></header><div class="scope-layout-list" data-scope-dropzone="${escapeHtml(group.key)}" ${collapsed?'hidden':''}>${group.passageIds.map((id,passageIndex)=>scopePassageRow(id,group.key,passageIndex)).join('')||'<p class="scope-layout-empty">Passage를 이곳으로 옮기세요.</p>'}</div></section>`;}
function renderScopeDetail(){
  const root=$('#scope-detail-content'), editor=state.scopeEditor;if(!root||!editor||!state.data)return;
  const scope=state.data.exams.find(item=>item.school===editor.school&&item.grade===editor.grade),available=state.data.passages.filter(p=>p.grade===editor.grade);if(!scope)return;
  if(!editor.layout)editor.layout=createScopeLayout(state.data.examPassages.filter(link=>link.exam_id===scope.id),scope.empty_passage_groups||[]);
  if(!editor.collapsedGroups)editor.collapsedGroups=new Set();
  const included=new Set(passageIds(editor.layout));
  root.innerHTML=`<div class="page-head scope-detail-head"><div><button class="back-link" type="button" data-close-scope-detail>← 시험범위</button><p class="eyebrow">${editor.school.startsWith('test')?'PRIVATE QA SCOPE':'CURRENT SCOPE'}</p><h1>${escapeHtml(editor.school)} · ${escapeHtml(editor.grade)}</h1><p class="lead">묶음과 Passage 순서는 저장 전까지 이 화면에서만 바뀝니다.</p></div></div><form data-set-scope-layout class="scope-detail-form"><div class="scope-detail-toolbar"><strong>${included.size}개 Passage · ${editor.layout.groups.length}개 묶음</strong><div class="scope-actions"><button class="button quiet" type="button" data-add-scope-group>+ 묶음 추가</button><button class="button primary" type="submit">시험범위 저장</button></div></div><div class="scope-layout">${editor.layout.groups.map(scopeGroup).join('')}<section class="scope-layout-group scope-layout-ungrouped"><header><div><strong>묶음 없음</strong><small>개별 Passage로 표시됩니다.</small></div></header><div class="scope-layout-list" data-scope-dropzone="">${editor.layout.ungrouped.map((id,index)=>scopePassageRow(id,UNGROUPED,index)).join('')||'<p class="scope-layout-empty">묶음 없는 Passage가 없습니다.</p>'}</div></section></div><details class="scope-membership"><summary>시험범위 Passage 추가·제외</summary><div class="scope-passage-grid">${available.map(p=>`<label class="scope-passage-row"><input type="checkbox" data-scope-toggle-passage="${p.id}" ${included.has(p.id)?'checked':''}><span><strong>${escapeHtml(p.title)}</strong><small>${p.source_type==='MOCK_EXAM'?'모의고사':'교과서'} · ${escapeHtml([p.source_year,p.source_month&&p.source_month+'월',p.source_label].filter(Boolean).join(' · ')||p.grade)}</small></span></label>`).join('')||'<div class="empty">이 학년에 등록된 Passage가 없습니다.</div>'}</div></details><div class="scope-detail-footer"><button class="button quiet" type="button" data-close-scope-detail>취소</button><button class="button primary" type="submit">시험범위 저장</button></div></form>`;
}
const impactLabels={sentences:'문장',questions:'문제',examLinks:'시험범위 연결',passageLinks:'포함 지문',attempts:'풀이 기록',savedWords:'저장 단어·표현',savedSentences:'저장 문장',wordLookups:'단어 조회 기록',translationViews:'해석 조회 기록'};
async function openDelete(targetType,targetId){
  const impact=await safely(()=>call('delete_impact',{targetType,targetId},state.token,'삭제 영향을 확인하는 중…'));if(!impact)return;state.deleteTarget={targetType,targetId,impact};
  const typeLabel={student:'학생',passage:'지문'}[targetType],counts=Object.entries(impact.counts).filter(([,count])=>count>0);
  $('#delete-title').textContent=`${impact.label}을 삭제할까요?`;
  $('#delete-content').innerHTML=`<p class="lead">${typeLabel}과 연결된 READY 학습 기록도 함께 삭제됩니다. 삭제한 데이터는 되돌릴 수 없습니다.</p>${counts.length?`<ul class="impact-list">${counts.map(([kind,count])=>`<li><span>${escapeHtml(impactLabels[kind]||kind)}</span><strong>${count}건</strong></li>`).join('')}</ul>`:'<p class="lead">연결 데이터가 없습니다.</p>'}<form id="delete-form" class="delete-actions"><button class="button quiet" type="button" data-close-delete>취소</button><button class="button danger" type="submit">삭제</button></form>`;
  $('#delete-modal').classList.add('on');$('#delete-modal').setAttribute('aria-hidden','false');
}
function closeDelete(){$('#delete-modal').classList.remove('on');$('#delete-modal').setAttribute('aria-hidden','true');state.deleteTarget=null;}
document.addEventListener('change',event=>{if(event.target.id==='factory-mode')syncFactoryMode();if(event.target.name==='school'&&event.target.closest('#create-student-form')&&['test','test2'].includes(event.target.value))event.target.form.elements.grade.value=event.target.value==='test'?'1학년':'2학년';if(event.target.id==='student-school-filter'||event.target.id==='student-grade-filter')renderStudents();if(event.target.dataset.selectPassage){if(event.target.checked)state.selectedPassageIds.add(event.target.dataset.selectPassage);else state.selectedPassageIds.delete(event.target.dataset.selectPassage);renderPassageSelection();}});
document.addEventListener('change',event=>{if(['passage-grade-filter','passage-type-filter','passage-year-filter','passage-month-filter'].includes(event.target.id)){state.passagePage=0;renderPassages();}});
document.addEventListener('change',event=>{if(event.target.id==='learning-school-filter'){state.learning.school=event.target.value;state.learning.data=null;loadLearningProgress();}if(event.target.id==='learning-grade-filter'){state.learning.grade=event.target.value;state.learning.data=null;loadLearningProgress();}if(event.target.id==='learning-sort'){state.learning.sort=event.target.value==='recent'?'recent':'oldest';renderLearningProgress();}});
document.addEventListener('input',event=>{const key=event.target.dataset.scopeGroupLabel;if(key===undefined||!state.scopeEditor?.layout)return;const group=state.scopeEditor.layout.groups.find(item=>item.key===key);if(group)group.label=event.target.value;});
document.addEventListener('change',event=>{if(!state.scopeEditor?.layout)return;const toggleId=event.target.dataset.scopeTogglePassage;if(toggleId){if(event.target.checked)movePassage(state.scopeEditor.layout,toggleId,UNGROUPED);else removePassage(state.scopeEditor.layout,toggleId);return renderScopeDetail();}const passageId=event.target.dataset.moveScopePassage;if(passageId!==undefined){movePassage(state.scopeEditor.layout,passageId,event.target.value||UNGROUPED);renderScopeDetail();}});
document.addEventListener('click',event=>{const button=event.target.closest('button');const layout=state.scopeEditor?.layout;if(!button||!layout)return;if(button.hasAttribute('data-add-scope-group')){addGroup(layout);return renderScopeDetail();}if(button.dataset.toggleScopeGroup!==undefined){const collapsed=state.scopeEditor.collapsedGroups||(state.scopeEditor.collapsedGroups=new Set());if(collapsed.has(button.dataset.toggleScopeGroup))collapsed.delete(button.dataset.toggleScopeGroup);else collapsed.add(button.dataset.toggleScopeGroup);return renderScopeDetail();}if(button.dataset.deleteScopeGroup!==undefined){removeGroup(layout,button.dataset.deleteScopeGroup);return renderScopeDetail();}if(button.dataset.moveGroupUp!==undefined||button.dataset.moveGroupDown!==undefined){const key=button.dataset.moveGroupUp??button.dataset.moveGroupDown,index=layout.groups.findIndex(group=>group.key===key),delta=button.dataset.moveGroupUp!==undefined?-1:2;moveGroup(layout,key,index+delta);return renderScopeDetail();}const passageId=button.dataset.movePassageUp??button.dataset.movePassageDown;if(passageId!==undefined){const row=button.closest('[data-scope-passage]'),groupKey=row?.dataset.scopeGroup||UNGROUPED,list=groupKey?layout.groups.find(group=>group.key===groupKey)?.passageIds:layout.ungrouped,index=list?.indexOf(passageId)??-1;if(index>=0)movePassage(layout,passageId,groupKey,index+(button.dataset.movePassageUp!==undefined?-1:1));return renderScopeDetail();}});
let scopeDrag=null;
document.addEventListener('dragstart',event=>{const passage=event.target.closest('[data-scope-passage]'),group=event.target.closest('[data-scope-group-card]');if(passage)scopeDrag={type:'passage',id:passage.dataset.scopePassage};else if(group)scopeDrag={type:'group',id:group.dataset.scopeGroupCard};else return;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',scopeDrag.id);});
document.addEventListener('dragover',event=>{if(scopeDrag&&event.target.closest('[data-scope-dropzone],[data-scope-group-card]')){event.preventDefault();event.dataTransfer.dropEffect='move';}});
document.addEventListener('drop',event=>{const layout=state.scopeEditor?.layout;if(!scopeDrag||!layout)return;event.preventDefault();if(scopeDrag.type==='group'){const target=event.target.closest('[data-scope-group-card]');if(target){moveGroup(layout,scopeDrag.id,layout.groups.findIndex(group=>group.key===target.dataset.scopeGroupCard));renderScopeDetail();}}else{const zone=event.target.closest('[data-scope-dropzone]'),target=event.target.closest('[data-scope-passage]');if(zone){const groupKey=zone.dataset.scopeDropzone||UNGROUPED,list=groupKey?layout.groups.find(group=>group.key===groupKey)?.passageIds:layout.ungrouped,sourceList=layout.groups.find(group=>group.passageIds.includes(scopeDrag.id))?.passageIds||layout.ungrouped,sourceIndex=sourceList.indexOf(scopeDrag.id);let targetIndex=target?list.indexOf(target.dataset.scopePassage):list.length;if(sourceList===list&&sourceIndex>=0&&sourceIndex<targetIndex)targetIndex-=1;movePassage(layout,scopeDrag.id,groupKey,targetIndex);renderScopeDetail();}}scopeDrag=null;});
document.addEventListener('dragend',()=>{scopeDrag=null;});
document.addEventListener('click',event=>{const button=event.target.closest('button');if(event.target.closest('[data-close-delete]'))return closeDelete();if(event.target.closest('[data-close-passage]'))return closePassage();if(button?.dataset.factoryDelete!==undefined){captureFactoryRows();state.factoryRows.splice(Number(button.dataset.factoryDelete),1);return renderFactoryReview({job:state.factoryJob});}if(button?.dataset.factoryAddAfter!==undefined){captureFactoryRows();state.factoryRows.splice(Number(button.dataset.factoryAddAfter)+1,0,{text:'',translation:''});return renderFactoryReview({job:state.factoryJob});}if(button?.hasAttribute('data-factory-finalize-incomplete'))return confirmFactory({finalize:true,allowIncomplete:true});if(button?.hasAttribute('data-factory-finalize'))return confirmFactory({finalize:true});if(button?.hasAttribute('data-factory-confirm'))return confirmFactory();if(button?.dataset.regenerateWorkbook)return regenerateFactoryWorkbook(button.dataset.regenerateWorkbook);if(button?.dataset.deleteStudent)return openDelete('student',button.dataset.deleteStudent);if(button?.dataset.deletePassage)return openDelete('passage',button.dataset.deletePassage);if(button?.dataset.openScopeSchool){state.scopeEditor={school:button.dataset.openScopeSchool,grade:button.dataset.openScopeGrade};return route('scope-detail');}if(button?.hasAttribute('data-close-scope-detail')){state.scopeEditor=null;return route('scopes');}if(button?.hasAttribute('data-clear-scope')){button.closest('form').querySelectorAll('[name="passageIds"]').forEach(input=>input.checked=false);return;}if(button?.hasAttribute('data-clear-passage-selection')){state.selectedPassageIds.clear();renderPassages();return;}if(button?.dataset.editPassage)return openPassage(button.dataset.editPassage);if(button?.dataset.passagePage){state.passagePage+=button.dataset.passagePage==='next'?1:-1;return renderPassages();}});
document.addEventListener('click',event=>{const period=event.target.closest('[data-learning-period]');if(period){state.learning.period=period.dataset.learningPeriod;state.learning.data=null;return loadLearningProgress();}const student=event.target.closest('[data-open-learning-student]');if(student)return openLearningStudent(student.dataset.openLearningStudent);const attempt=event.target.closest('[data-open-learning-attempt]');if(attempt)return openLearningAttempt(attempt.dataset.openLearningAttempt,attempt.dataset.learningAttemptKind);if(event.target.closest('[data-close-learning-student]')){state.learning.detail=null;state.learning.replay=null;return renderLearningProgress();}if(event.target.closest('[data-close-learning-attempt]')){state.learning.replay=null;const root=$('#learning-attempt-replay');if(root){root.hidden=true;root.innerHTML='';}}});
document.addEventListener('submit',async event=>{const form=event.target;if(form.id!=='delete-form')return;event.preventDefault();const target=state.deleteTarget;if(!target)return;const op={student:'delete_student',passage:'delete_passage'}[target.targetType],idKey={student:'studentId',passage:'passageId'}[target.targetType];const data=await safely(()=>call(op,{[idKey]:target.targetId},state.token,'연결 데이터를 함께 삭제하는 중…'));if(data){closeDelete();state.selectedPassageIds.delete(target.targetId);await loadAdmin();toast('연결된 READY 데이터까지 삭제했습니다.');}});
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.route)return route(button.dataset.route);if(button.id==='theme-toggle')return applyTheme(document.body.classList.contains('dark')?'light':'dark');if(button.id==='admin-logout')return logout();if(button.id==='refresh-progress'){state.learning.data=null;return loadLearningProgress();}if(['refresh-admin','refresh-passages','refresh-exams'].includes(button.id))return loadAdmin();});
document.addEventListener('submit',event=>{if(event.target.id!=='question-import-form')return;event.preventDefault();importQuestionBundle(event.target);});
document.addEventListener('submit',event=>{if(event.target.id!=='factory-start-form')return;event.preventDefault();startFactory(event.target);});
document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target,formData=new FormData(form),values=Object.fromEntries(formData);if(form.id==='admin-login-form')return login(form);if(form.id==='create-student-form'){const data=await safely(()=>call('create_student',values));if(data){form.reset();await loadAdmin();}return;}if(form.id==='assign-passages-to-scope'){const passageIds=[...state.selectedPassageIds],data=await safely(()=>call('assign_scope_passages',{school:values.school,grade:values.grade,passageIds},state.token,'시험범위에 지문을 배정하는 중…'));if(data){state.selectedPassageIds.clear();await loadAdmin();route('scopes');toast(`${passageIds.length}개 지문을 배정했습니다.`);}return;}if(form.hasAttribute('data-set-scope-layout')){const editor=state.scopeEditor,scope=state.data.exams.find(item=>item.school===editor.school&&item.grade===editor.grade),layout=flattenScopeLayout(editor.layout),emptyGroups=emptyGroupDefinitions(editor.layout);if(editor.layout.groups.some(group=>!group.label.trim()))return toast('묶음 이름을 입력해 주세요.');const data=await safely(()=>call('set_scope_layout',{examId:scope.id,layout,emptyGroups},state.token,'묶음과 순서를 저장하는 중…'));if(data){await loadAdmin();state.scopeEditor={school:editor.school,grade:editor.grade};renderScopeDetail();toast('시험범위 묶음과 순서를 저장했습니다.');}return;}if(form.id==='update-passage-form'){const data=await safely(()=>call('update_passage',{...values,passageId:state.passageEditorId},state.token,'지문을 저장하는 중…'));if(data){closePassage();await loadAdmin();toast('지문 정보를 저장했습니다.');}return;}if(form.dataset.resetCode){const data=await safely(()=>call('set_student_code',{studentId:form.dataset.resetCode,code:values.code}));if(data){form.reset();toast('학생 코드를 변경하고 기존 학생 세션을 종료했습니다.');}return;}});
document.addEventListener('keydown',event=>{const student=event.target.closest?.('[data-open-learning-student]');if(student&&(event.key==='Enter'||event.key===' ')){event.preventDefault();return openLearningStudent(student.dataset.openLearningStudent);}if(event.key!=='Escape')return;if($('#passage-modal').classList.contains('on'))closePassage();if($('#delete-modal').classList.contains('on'))closeDelete();});
applyTheme(localStorage.getItem('ready-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));try{const previous=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(previous?.token){state.token=previous.token;loadAdmin();}else showLogin();}catch{showLogin();}
