import { readyApi } from '../api.js';

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const SESSION_KEY = 'ready-admin-session';
const state = { token:'', data:null, route:'students', passageEditorId:null, deleteTarget:null, passagePage:0, selectedPassageIds:new Set(), scopeEditor:null };
const SCOPE_SCHOOLS=['중앙고','동고','신흥고','한빛고'], SCOPE_GRADES=['1학년','2학년'];
let busyCount = 0, toastTimer;
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
function setBusy(on, label='잠시만요…') { busyCount=Math.max(0,busyCount+(on?1:-1)); $('#busy').hidden=!busyCount; $('#busy span:last-child').textContent=label; }
function toast(message) { $('#toast').textContent=message; $('#toast').classList.add('on'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('on'),3200); }
function applyTheme(theme) { const dark=theme==='dark'; document.documentElement.classList.toggle('dark',dark); document.body.classList.toggle('dark',dark); localStorage.setItem('ready-theme',theme); }
function clearSession() { sessionStorage.removeItem(SESSION_KEY); state.token=''; state.data=null; }
async function call(op,data={},token=state.token,label='잠시만요…') { setBusy(true,label); try{return await readyApi(op,data,token);}finally{setBusy(false);} }
async function safely(job,{auth=true}={}) { try{return await job();}catch(error){if(auth&&error.status===401){clearSession();showLogin();}toast(error.message||'요청을 처리하지 못했습니다.');return null;} }
function showLogin() { $('#admin-login').hidden=false; $('#admin-nav').hidden=true; $('#admin-logout').hidden=true; $$('.view').forEach(view=>view.classList.remove('on')); }
function route(name) { state.route=name; $$('.view').forEach(view=>view.classList.toggle('on',view.id===`v-${name}`)); $$('.navbtn').forEach(button=>button.classList.toggle('on',button.dataset.route===(name==='scope-detail'?'scopes':name))); if(name==='scope-detail')renderScopeDetail(); }
async function login(form) { const password=new FormData(form).get('password'); const data=await safely(()=>call('admin_login',{password},'','관리자 비밀번호를 확인하는 중…'),{auth:false}); form.reset(); if(!data)return; state.token=data.session.token; sessionStorage.setItem(SESSION_KEY,JSON.stringify(data.session)); await loadAdmin(); }
async function loadAdmin() { const data=await safely(()=>call('teacher_bootstrap',{},state.token,'관리자 화면을 불러오는 중…')); if(!data)return; state.data=data; $('#admin-login').hidden=true; $('#admin-nav').hidden=false; $('#admin-logout').hidden=false; renderStudents(); renderPassages(); renderScopes(); route(state.route); }
async function logout() { if(state.token)await safely(()=>call('logout')); clearSession(); showLogin(); }
async function importQuestionBundle(form) {
  const file=new FormData(form).get('bundle');
  if(!(file instanceof File)||!file.size)return toast('가져올 JSON 파일을 선택해 주세요.');
  let bundle;
  try{bundle=JSON.parse(await file.text());}catch{return toast('올바른 JSON 문제 번들이 아닙니다.');}
  const questions=Array.isArray(bundle)?bundle:bundle?.questions;
  if(!Array.isArray(questions)||!questions.length)return toast('가져올 READY 문항이 없습니다.');
  if(questions.some(question=>question?.status!=='available'||question?.payload?.import_status!=='ready'))return toast('READY가 아닌 문항이 포함되어 가져오기를 중단했습니다.');
  const data=await safely(()=>call('import_questions',{questions},state.token,`${questions.length}개 READY 문항을 가져오는 중…`));
  if(!data)return;
  form.reset();await loadAdmin();route('passages');toast(`${data.imported||questions.length}개 READY 문항을 가져왔습니다.`);
}
function passagesForExam(examId){const byId=new Map(state.data.passages.map(passage=>[passage.id,passage]));return state.data.examPassages.filter(link=>link.exam_id===examId).sort((a,b)=>a.position-b.position).map(link=>byId.get(link.passage_id)).filter(Boolean);}

function renderStudents() {
  const school=$('#student-school-filter')?.value||'',grade=$('#student-grade-filter')?.value||'';
  const students=state.data.students.filter(student=>(!school||student.school===school)&&(!grade||student.grade===grade));
  const root=$('#admin-students');
  root.innerHTML=students.length?`<div class="table-wrap student-table"><table><thead><tr><th>이름</th><th>학교 / 학년</th><th>학생 코드 변경</th><th></th></tr></thead><tbody>${students.map(student=>`<tr><td><strong>${escapeHtml(student.name)}</strong></td><td>${escapeHtml(student.school)} · ${escapeHtml(student.grade)}</td><td><form class="pin-reset" data-reset-code="${student.id}"><input name="code" type="password" inputmode="numeric" pattern="[0-9]{6}" minlength="6" maxlength="6" autocomplete="new-password" placeholder="새 6자리 코드" required><button class="button quiet small" type="submit">변경</button></form></td><td><button class="button danger small" type="button" data-delete-student="${student.id}">삭제</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">조건에 맞는 학생이 없습니다.</div>';
}
function renderPassageSelection(){
  const root=$('#passage-selection'), selected=state.data.passages.filter(p=>state.selectedPassageIds.has(p.id)); if(!root)return;
  if(!selected.length){root.innerHTML='';return;}
  const grades=[...new Set(selected.map(p=>p.grade))], mixed=grades.length!==1;
  root.innerHTML=`<section class="card passage-selection"><div class="selection-summary"><strong>${selected.length}개 지문 선택</strong><button class="button quiet small" type="button" data-clear-passage-selection>선택 해제</button></div>${mixed?'<div class="result bad">같은 학년 지문만 하나의 시험범위에 배정할 수 있습니다.</div>':`<form id="assign-passages-to-scope" class="form-grid scope-assign"><label><span>학교</span><select name="school" required>${SCOPE_SCHOOLS.map(school=>`<option>${school}</option>`).join('')}</select></label><label><span>학년</span><input name="grade" value="${escapeHtml(grades[0])}" readonly></label><button class="button primary" type="submit">선택한 지문 배정</button></form>`}</section>`;
}
function renderPassages(){const root=$('#passage-library');if(!root)return;const validIds=new Set(state.data.passages.map(p=>p.id));state.selectedPassageIds=new Set([...state.selectedPassageIds].filter(id=>validIds.has(id)));const grade=$('#passage-grade-filter')?.value||'',type=$('#passage-type-filter')?.value||'',year=$('#passage-year-filter')?.value||'',month=$('#passage-month-filter')?.value||'';const rows=state.data.passages.filter(p=>(!grade||p.grade===grade)&&(!type||p.source_type===type)&&(!year||String(p.source_year)===year)&&(!month||String(p.source_month)===month));const pageSize=15,totalPages=Math.max(1,Math.ceil(rows.length/pageSize));state.passagePage=Math.min(state.passagePage,totalPages-1);const page=rows.slice(state.passagePage*pageSize,(state.passagePage+1)*pageSize);root.innerHTML=`<div class="library-note"><span>지문을 체크해 시험범위에 배정하세요.</span></div><div class="table-wrap"><table><thead><tr><th>선택</th><th>제목</th><th>종류</th><th>학년</th><th>출처</th><th></th></tr></thead><tbody>${page.map(p=>`<tr data-passage-row="${p.id}"><td><input class="passage-check" type="checkbox" aria-label="${escapeHtml(p.title)} 선택" data-select-passage="${p.id}" ${state.selectedPassageIds.has(p.id)?'checked':''}></td><td><button class="text-button" type="button" data-edit-passage="${p.id}">${escapeHtml(p.title)}</button></td><td>${p.source_type==='MOCK_EXAM'?'모의고사':'교과서'}</td><td>${escapeHtml(p.grade)}</td><td>${escapeHtml([p.source_year,p.source_month&&p.source_month+'월',p.source_label].filter(Boolean).join(' · ')||'—')}</td><td><button class="button quiet small" type="button" data-edit-passage="${p.id}">수정</button><button class="button danger small" type="button" data-delete-passage="${p.id}">삭제</button></td></tr>`).join('')||'<tr><td colspan="6">조건에 맞는 지문이 없습니다.</td></tr>'}</tbody></table></div><div class="pagination"><button class="button quiet small" type="button" data-passage-page="prev" ${state.passagePage===0?'disabled':''}>← Prev</button><span>${state.passagePage+1} / ${totalPages}</span><button class="button quiet small" type="button" data-passage-page="next" ${state.passagePage===totalPages-1?'disabled':''}>Next →</button></div>`;renderPassageSelection();}
function openPassage(passageId){const passage=state.data.passages.find(item=>item.id===passageId);if(!passage)return;state.passageEditorId=passageId;$('#passage-editor').innerHTML=`<form id="update-passage-form"><div class="form-grid"><label><span>제목</span><input name="title" value="${escapeHtml(passage.title)}" required></label><label><span>종류</span><select name="sourceType"><option value="TEXTBOOK" ${passage.source_type==='TEXTBOOK'?'selected':''}>교과서</option><option value="MOCK_EXAM" ${passage.source_type==='MOCK_EXAM'?'selected':''}>모의고사</option></select></label><label><span>학년</span><select name="grade">${['1학년','2학년','3학년'].map(value=>`<option ${passage.grade===value?'selected':''}>${value}</option>`).join('')}</select></label><label><span>연도</span><input name="sourceYear" value="${passage.source_year||''}"></label><label><span>월</span><input name="sourceMonth" value="${passage.source_month||''}"></label></div><p class="lead compact">문장과 해석은 등록 시 확정한 행을 그대로 사용합니다.</p><button class="button primary" type="submit">지문 정보 저장</button></form>`;$('#passage-modal').classList.add('on');$('#passage-modal').setAttribute('aria-hidden','false');}
function closePassage(){$('#passage-modal').classList.remove('on');$('#passage-modal').setAttribute('aria-hidden','true');state.passageEditorId=null;}
function renderScopes() {
  const root=$('#teacher-exams');
  root.innerHTML=SCOPE_SCHOOLS.map(school=>`<section class="scope-school"><h2>${school}</h2><div class="scope-grid">${SCOPE_GRADES.map(grade=>{const scope=state.data.exams.find(item=>item.school===school&&item.grade===grade),passages=scope?passagesForExam(scope.id):[];return `<button class="card scope-card scope-card-button" type="button" data-open-scope-school="${school}" data-open-scope-grade="${grade}"><div class="card-head"><div><p class="eyebrow">CURRENT SCOPE</p><h3>${grade}</h3><p class="lead compact">지문 ${passages.length}개</p></div><span class="scope-card-arrow" aria-hidden="true">→</span></div><div class="passage-list">${passages.slice(0,4).map((p,index)=>`<div class="recent-row"><span>${index+1}. ${escapeHtml(p.title)}</span></div>`).join('')||'<div class="empty compact-empty">아직 배정된 지문이 없습니다.</div>'}${passages.length>4?`<p class="lead compact">외 ${passages.length-4}개</p>`:''}</div><span class="scope-card-cta">눌러서 지문 추가·제외</span></button>`;}).join('')}</div></section>`).join('');
}
function renderScopeDetail(){
  const root=$('#scope-detail-content'), editor=state.scopeEditor;if(!root||!editor||!state.data)return;
  const scope=state.data.exams.find(item=>item.school===editor.school&&item.grade===editor.grade),passages=scope?passagesForExam(scope.id):[],included=new Set(passages.map(p=>p.id)),available=state.data.passages.filter(p=>p.grade===editor.grade);
  root.innerHTML=`<div class="page-head scope-detail-head"><div><button class="back-link" type="button" data-close-scope-detail>← 시험범위</button><p class="eyebrow">CURRENT SCOPE</p><h1>${escapeHtml(editor.school)} · ${escapeHtml(editor.grade)}</h1><p class="lead">현재 ${passages.length}개 지문 · 체크한 지문만 학생에게 표시됩니다.</p></div></div><form data-set-scope class="scope-detail-form"><input type="hidden" name="school" value="${escapeHtml(editor.school)}"><input type="hidden" name="grade" value="${escapeHtml(editor.grade)}"><div class="scope-detail-toolbar"><strong>${available.length}개 Passage</strong><div class="scope-actions"><button class="button quiet" type="button" data-clear-scope>전체 선택 해제</button><button class="button primary" type="submit">시험범위 저장</button></div></div><div class="scope-passage-grid">${available.map(p=>`<label class="scope-passage-row"><input type="checkbox" name="passageIds" value="${p.id}" ${included.has(p.id)?'checked':''}><span><strong>${escapeHtml(p.title)}</strong><small>${p.source_type==='MOCK_EXAM'?'모의고사':'교과서'} · ${escapeHtml([p.source_year,p.source_month&&p.source_month+'월',p.source_label].filter(Boolean).join(' · ')||p.grade)}</small></span></label>`).join('')||'<div class="empty">이 학년에 등록된 Passage가 없습니다.</div>'}</div><div class="scope-detail-footer"><button class="button quiet" type="button" data-close-scope-detail>취소</button><button class="button primary" type="submit">시험범위 저장</button></div></form>`;
}
const impactLabels={sentences:'문장',questions:'문제',examLinks:'시험범위 연결',passageLinks:'포함 지문',attempts:'풀이 기록',savedWords:'저장 단어·표현',savedSentences:'저장 문장',wordLookups:'단어 조회 기록',translationViews:'해석 조회 기록'};
async function openDelete(targetType,targetId){
  const impact=await safely(()=>call('delete_impact',{targetType,targetId},state.token,'삭제 영향을 확인하는 중…'));if(!impact)return;state.deleteTarget={targetType,targetId,impact};
  const typeLabel={student:'학생',passage:'지문'}[targetType],counts=Object.entries(impact.counts).filter(([,count])=>count>0);
  $('#delete-title').textContent=`${impact.label}을 삭제할까요?`;
  $('#delete-content').innerHTML=`<p class="lead">${typeLabel}과 연결된 READY 학습 기록도 함께 삭제됩니다. 삭제한 데이터는 되돌릴 수 없습니다.</p>${counts.length?`<ul class="impact-list">${counts.map(([kind,count])=>`<li><span>${escapeHtml(impactLabels[kind]||kind)}</span><strong>${count}건</strong></li>`).join('')}</ul>`:'<p class="lead">연결 데이터가 없습니다.</p>'}<form id="delete-form" class="delete-actions"><button class="button quiet" type="button" data-close-delete>취소</button><button class="button danger" type="submit">삭제</button></form>`;
  $('#delete-modal').classList.add('on');$('#delete-modal').setAttribute('aria-hidden','false');
}
function closeDelete(){$('#delete-modal').classList.remove('on');$('#delete-modal').setAttribute('aria-hidden','true');state.deleteTarget=null;}
document.addEventListener('change',event=>{if(event.target.id==='student-school-filter'||event.target.id==='student-grade-filter')renderStudents();if(event.target.dataset.selectPassage){if(event.target.checked)state.selectedPassageIds.add(event.target.dataset.selectPassage);else state.selectedPassageIds.delete(event.target.dataset.selectPassage);renderPassageSelection();}});
document.addEventListener('change',event=>{if(['passage-grade-filter','passage-type-filter','passage-year-filter','passage-month-filter'].includes(event.target.id)){state.passagePage=0;renderPassages();}});
document.addEventListener('click',event=>{const button=event.target.closest('button');if(event.target.closest('[data-close-delete]'))return closeDelete();if(event.target.closest('[data-close-passage]'))return closePassage();if(button?.dataset.deleteStudent)return openDelete('student',button.dataset.deleteStudent);if(button?.dataset.deletePassage)return openDelete('passage',button.dataset.deletePassage);if(button?.dataset.openScopeSchool){state.scopeEditor={school:button.dataset.openScopeSchool,grade:button.dataset.openScopeGrade};return route('scope-detail');}if(button?.hasAttribute('data-close-scope-detail')){state.scopeEditor=null;return route('scopes');}if(button?.hasAttribute('data-clear-scope')){button.closest('form').querySelectorAll('[name="passageIds"]').forEach(input=>input.checked=false);return;}if(button?.hasAttribute('data-clear-passage-selection')){state.selectedPassageIds.clear();renderPassages();return;}if(button?.dataset.editPassage)return openPassage(button.dataset.editPassage);if(button?.dataset.passagePage){state.passagePage+=button.dataset.passagePage==='next'?1:-1;return renderPassages();}});
document.addEventListener('submit',async event=>{const form=event.target;if(form.id!=='delete-form')return;event.preventDefault();const target=state.deleteTarget;if(!target)return;const op={student:'delete_student',passage:'delete_passage'}[target.targetType],idKey={student:'studentId',passage:'passageId'}[target.targetType];const data=await safely(()=>call(op,{[idKey]:target.targetId},state.token,'연결 데이터를 함께 삭제하는 중…'));if(data){closeDelete();state.selectedPassageIds.delete(target.targetId);await loadAdmin();toast('연결된 READY 데이터까지 삭제했습니다.');}});
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.route)return route(button.dataset.route);if(button.id==='theme-toggle')return applyTheme(document.body.classList.contains('dark')?'light':'dark');if(button.id==='admin-logout')return logout();if(['refresh-admin','refresh-passages','refresh-exams'].includes(button.id))return loadAdmin();});
document.addEventListener('submit',event=>{if(event.target.id!=='question-import-form')return;event.preventDefault();importQuestionBundle(event.target);});
document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target,formData=new FormData(form),values=Object.fromEntries(formData);if(form.id==='admin-login-form')return login(form);if(form.id==='create-student-form'){const data=await safely(()=>call('create_student',values));if(data){form.reset();await loadAdmin();}return;}if(form.id==='assign-passages-to-scope'){const passageIds=[...state.selectedPassageIds],data=await safely(()=>call('assign_scope_passages',{school:values.school,grade:values.grade,passageIds},state.token,'시험범위에 지문을 배정하는 중…'));if(data){state.selectedPassageIds.clear();await loadAdmin();route('scopes');toast(`${passageIds.length}개 지문을 배정했습니다.`);}return;}if(form.hasAttribute('data-set-scope')){const passageIds=[...formData.getAll('passageIds')],data=await safely(()=>call('set_scope_passages',{school:values.school,grade:values.grade,passageIds},state.token,'시험범위를 저장하는 중…'));if(data){await loadAdmin();renderScopeDetail();toast('현재 시험범위를 저장했습니다.');}return;}if(form.id==='update-passage-form'){const data=await safely(()=>call('update_passage',{...values,passageId:state.passageEditorId},state.token,'지문을 저장하는 중…'));if(data){closePassage();await loadAdmin();toast('지문 정보를 저장했습니다.');}return;}if(form.dataset.resetCode){const data=await safely(()=>call('set_student_code',{studentId:form.dataset.resetCode,code:values.code}));if(data){form.reset();toast('학생 코드를 변경하고 기존 학생 세션을 종료했습니다.');}return;}});
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if($('#passage-modal').classList.contains('on'))closePassage();if($('#delete-modal').classList.contains('on'))closeDelete();});
applyTheme(localStorage.getItem('ready-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));try{const previous=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(previous?.token){state.token=previous.token;loadAdmin();}else showLogin();}catch{showLogin();}
