import {selectToken} from './studio-selection.js';
import {AUTHORED,PURE,STEPS,LABELS,fieldFor,dirtyRows,spanTokens,tokenSpan} from './studio-contract.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let api,toast,refresh,openPassage,current=null,step='english_blank',onlyDirty=false,batch=[],localEdits=new Map(),activeSpan=null;
let previewItems=[],previewIndex=0,previewResponses=new Map(),previewRevealed=false;

export function initStudio(adapters){({api,toast,refresh,openPassage}=adapters);}
const root=()=>document.querySelector('#studio-authoring');

export async function attachStudio(passageId){
 const result=await api('studio_open',{passageId});if(!result)return;
 current=result;localEdits.clear();activeSpan=null;step='english_blank';onlyDirty=false;previewItems=[];
 document.querySelector('#studio-authoring')?.remove();document.querySelector('.studio-flow')?.remove();
 document.querySelector('.studio-flow-host')?.insertAdjacentHTML('beforeend','<nav class="studio-flow" aria-label="Passage 작업"><button class="active" type="button" data-studio-mode="edit">Passage 편집</button><button type="button" data-studio-mode="authoring">Authoring / Preview</button></nav>');
 document.querySelector('#passage-editor').insertAdjacentHTML('beforeend','<section id="studio-authoring"></section>');
 render();root().hidden=true;document.querySelector('#update-passage-form').hidden=false;
}

function allConfirmed(stage){return current.rows.filter(row=>row.blockType==='SENTENCE').every(row=>current.studio.annotations[row.id]?.steps[stage]?.status==='confirmed');}
function chip(stageName){const authored=AUTHORED.includes(stageName),complete=authored&&allConfirmed(stageName),published=current.studio.publishedSteps?.includes(stageName);return `<button type="button" data-studio-step="${stageName}" class="${stageName===step?'active ':''}${complete||published?'is-confirmed':''}"><span>${LABELS[stageName]}</span><small>${authored?(complete?'확정':'검토 필요'):'AUTO'}</small></button>`;}
function status(record){return record?.status==='confirmed'?'확정':record?.status==='stale'?'수정 후 재검토':'검토 필요';}
function tokens(row,record){const text=row[fieldFor(step)],words=spanTokens(text),targets=record.targets||[];let output='',cursor=0;for(let i=0;i<words.length;i++){const word=words[i],targetIndex=targets.findIndex(target=>i>=target.span.tokenStart&&i<target.span.tokenEnd),selected=targetIndex>=0,active=selected&&activeSpan?.rowId===row.id&&activeSpan?.step===step&&activeSpan.index===targetIndex;output+=esc(text.slice(cursor,word.start));output+=`<button type="button" class="studio-word ${selected?'is-target':''} ${active?'is-editing':''}" data-token="${i}" data-row="${row.id}" aria-pressed="${selected}">${esc(word.text)}</button>`;cursor=word.end;}return output+esc(text.slice(cursor));}
function stageRow(label,items){return `<section class="studio-stage-row"><span>${label}</span><div class="studio-chips">${items.map(chip).join('')}</div></section>`;}
function render(){if(!current||!root())return;const {rows,studio}=current,dirty=new Set(dirtyRows(rows,studio.annotations).map(row=>row.id)),visible=rows.filter(row=>row.blockType==='SENTENCE'&&(!onlyDirty||dirty.has(row.id)));root().innerHTML=`<div class="studio-head"><div><p class="eyebrow">AUTHORING</p><h2>Workbook 단계 편집</h2><p>자동 단계는 바로 Preview하고, Authoring 단계는 출제 표현을 고른 뒤 해당 단계만 발행하세요.</p></div><button class="button quiet" type="button" data-studio-author>AI Authoring · ${dirty.size}문장</button></div><div class="studio-stage-groups">${stageRow('Auto',STEPS.filter(stageName=>PURE.includes(stageName)))}${stageRow('Authoring',STEPS.filter(stageName=>AUTHORED.includes(stageName)))}</div><div class="studio-tools"><label><input type="checkbox" data-studio-dirty ${onlyDirty?'checked':''}> 검토할 문장만</label><button type="button" class="button quiet small" data-studio-preview>학생용 Preview</button></div><div id="studio-preview"></div>${PURE.includes(step)?'<p class="empty">이 단계는 Canonical Passage에서 자동 생성됩니다. 바로 Preview하거나 발행할 수 있습니다.</p>':visible.map((row,index)=>{const record=studio.annotations[row.id]?.steps[step]||{targets:[]};return `<article class="studio-sentence" data-sentence="${row.id}"><header><span>${index+1} · ${status(record)}</span><button type="button" class="button quiet small" data-studio-confirm="${row.id}">${record.targets.length?'문장 확정':'출제 표현 없음 · 확정'}</button></header><p class="studio-prose" lang="${step==='korean_blank'?'ko':'en'}">${tokens(row,record)}</p><p class="studio-translation">${esc(row[fieldFor(step)==='text'?'translation':'text'])}</p><div class="studio-target-controls">${record.targets.map((target,n)=>`<button class="button quiet small" type="button" data-edit-target="${n}" data-row="${row.id}">${esc(target.span.quote)}${['verb_form','grammar_choice'].includes(step)?' · 정답 편집':''}</button>`).join('')}</div><div class="studio-target-editor"></div></article>`;}).join('')}<footer class="studio-footer"><span>${allConfirmed(step)||PURE.includes(step)?'이 단계 발행 가능':`${dirty.size}문장 검토 필요`}</span><button type="button" class="button primary" data-studio-publish-step>이 단계 확정 및 발행</button></footer>`;}
function rowFor(id){return current.rows.find(row=>row.id===id);}
function recordFor(id){return current.studio.annotations[id].steps[step];}
function clickToken(id,index){const row=rowFor(id),record=recordFor(id),text=row[fieldFor(step)],currentIndex=activeSpan?.rowId===id&&activeSpan?.step===step?activeSpan.index:null,next=selectToken(record.targets,currentIndex,index);next.targets=next.targets.map(target=>{const span=tokenSpan(text,target.span.tokenStart,target.span.tokenEnd,id),changed=span.quote!==target.span.quote;return {...target,span,...(step==='verb_form'?{hint:target.hint||'',answer:span.quote}:{}),...(step==='grammar_choice'?{correct:span.quote,distractor:changed?'':target.distractor||''}:{})};});record.targets=next.targets;record.status='review';activeSpan=next.activeIndex===null?null:{rowId:id,step,index:next.activeIndex};localEdits.set(`${id}:${step}`,structuredClone(record));render();}
function editTarget(id,index){const target=recordFor(id).targets[index],element=root().querySelector(`[data-sentence="${id}"] .studio-target-editor`);if(!['verb_form','grammar_choice'].includes(step)){activeSpan={rowId:id,step,index};return render();}element.innerHTML=`<form data-target-form="${id}" data-index="${index}"><strong>${esc(target.span.quote)}</strong>${step==='verb_form'?`<label>원형 / 힌트<input name="hint" value="${esc(target.hint)}" required></label><label>정답<input name="answer" value="${esc(target.answer)}" required></label>`:`<label>정답<input name="correct" value="${esc(target.correct)}" required></label><label>오답<input name="distractor" value="${esc(target.distractor)}" required></label>`}<button class="button quiet small" type="submit">적용</button></form>`;element.querySelector('input')?.focus();}
async function action(op,extra={}){const result=await api(op,{passageId:current.passage.id,revision:current.passage.canonical_revision,version:current.studio.version,...extra});if(result?.studio){if(op==='studio_confirm_step')for(const item of extra.confirmations||[{sentenceId:extra.sentenceId}])localEdits.delete(`${item.sentenceId}:${extra.step}`);current.studio=result.studio;for(const [key,value] of localEdits){const [id,stageName]=key.split(':');current.studio.annotations[id].steps[stageName]=value;}render();}return result;}

function previewResponse(item){if(!previewResponses.has(item.key))previewResponses.set(item.key,[]);return previewResponses.get(item.key);}
function previewPrompt(item,response){let slot=0;const prompt=esc(item.prompt||'');if(item.kind==='choice_groups')return prompt.replace(/⟦CHOICE:(\d+)⟧/g,(_,raw)=>{const index=Number(raw);return `<span class="workbook-choice-group">${(item.groups?.[index]||[]).map(value=>`<button type="button" class="workbook-choice ${response[index]===value?'selected':''}" data-preview-choice="${index}" data-preview-value="${esc(value)}">${esc(value)}</button>`).join('')}</span>`;});if(item.kind==='reorder_groups'){const words=item.groups?.[0]||[];return `<div class="workbook-order-built">${esc(response[0]||'')}</div><div class="workbook-order-bank">${words.map(word=>`<button type="button" data-preview-order="${esc(word)}">${esc(word)}</button>`).join('')}</div>`;}if(['translation_input','full_sentence_input'].includes(item.kind))return `<textarea rows="4" data-preview-input placeholder="답을 입력하세요">${esc(response[0]||'')}</textarea>`;return prompt.replace(/_{5,}/g,()=>`<input class="studio-preview-blank" data-preview-blank="${slot}" value="${esc(response[slot++]||'')}" placeholder="빈칸">`);}
function renderPreview(){const host=document.querySelector('#studio-preview');if(!host)return;const item=previewItems[previewIndex];if(!item){host.innerHTML='<p class="empty">이 단계에는 발행할 항목이 없습니다.</p>';return;}const response=previewResponse(item);host.innerHTML=`<section class="student-preview-shell"><header class="workbook-study-head"><button type="button" data-preview-close aria-label="Preview 닫기">‹</button><strong>${previewIndex+1} / ${previewItems.length}</strong><span>☆</span></header><article class="workbook-card workbook-focus-card">${item.source?`<blockquote>${esc(item.source)}</blockquote>`:''}<div class="workbook-prompt">${previewPrompt(item,response)}</div>${previewRevealed?`<div class="preview-answer"><small>정답</small><strong>${(item.answers||[]).map(esc).join(' / ')||'확인 완료'}</strong></div>`:''}<footer class="preview-actions"><button class="button quiet" type="button" data-preview-answer>정답 바로 보기</button><button class="button primary" type="button" data-preview-next>${previewIndex===previewItems.length-1?'처음으로':'다음 문제'}</button></footer></article></section>`;}

document.addEventListener('click',async event=>{const button=event.target.closest('[data-studio-mode]');if(!button||!current)return;const form=document.querySelector('#update-passage-form');document.querySelectorAll('[data-studio-mode]').forEach(item=>item.classList.toggle('active',item===button));if(button.dataset.studioMode==='edit'){form.hidden=false;if(root())root().hidden=true;return;}const fields=[...document.querySelectorAll('[data-canonical-en]')],translations=[...document.querySelectorAll('[data-canonical-ko]')],types=[...document.querySelectorAll('[data-canonical-type]')];if(fields.length!==current.rows.length||fields.some((element,index)=>element.value!==current.rows[index].text||translations[index].value!==current.rows[index].translation||types[index].value!==current.rows[index].blockType))return toast('Passage 변경을 먼저 저장해 주세요.');form.hidden=true;root().hidden=false;});
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button||!button.closest('#studio-authoring'))return;if(button.dataset.studioStep){step=button.dataset.studioStep;activeSpan=null;previewItems=[];return render();}if(button.hasAttribute('data-studio-author')){if(localEdits.size)return toast('선택한 표현을 문장별로 확정한 뒤 Authoring을 실행하세요.');const result=await action('studio_author');if(result){onlyDirty=true;render();toast(`${result.dirtySentenceIds.length}문장 후보를 준비했습니다.`);}return;}if(button.dataset.token!==undefined)return clickToken(button.dataset.row,Number(button.dataset.token));if(button.dataset.editTarget!==undefined)return editTarget(button.dataset.row,Number(button.dataset.editTarget));if(button.dataset.studioConfirm){const id=button.dataset.studioConfirm;return action('studio_confirm_step',{sentenceId:id,step,targets:recordFor(id).targets});}if(button.hasAttribute('data-studio-publish-step')){if(AUTHORED.includes(step)){const confirmations=current.rows.filter(row=>row.blockType==='SENTENCE').map(row=>({sentenceId:row.id,targets:recordFor(row.id).targets}));const confirmed=await action('studio_confirm_step',{step,confirmations});if(!confirmed)return;}const result=await action('studio_publish',{step});if(result){await refresh();toast(`${LABELS[step]} 단계를 확정하고 발행했습니다.`);}return;}if(button.hasAttribute('data-studio-preview')){const result=await action('studio_preview');if(result){previewItems=result.catalog.stages.find(stageItem=>stageItem.semanticType===step)?.items||[];previewIndex=0;previewResponses.clear();previewRevealed=false;renderPreview();}return;}if(button.hasAttribute('data-preview-close')){previewItems=[];document.querySelector('#studio-preview').innerHTML='';return;}if(button.hasAttribute('data-preview-answer')){previewRevealed=!previewRevealed;return renderPreview();}if(button.hasAttribute('data-preview-next')){previewIndex=(previewIndex+1)%previewItems.length;previewRevealed=false;return renderPreview();}const item=previewItems[previewIndex];if(!item)return;if(button.dataset.previewChoice!==undefined){previewResponse(item)[Number(button.dataset.previewChoice)]=button.dataset.previewValue;return renderPreview();}if(button.dataset.previewOrder!==undefined){previewResponse(item)[0]=`${previewResponse(item)[0]||''} ${button.dataset.previewOrder}`.trim();return renderPreview();}});
document.addEventListener('change',event=>{if(event.target.hasAttribute('data-studio-dirty')){onlyDirty=event.target.checked;render();}});
document.addEventListener('input',event=>{const host=event.target.closest('#studio-preview'),item=previewItems[previewIndex];if(!host||!item)return;if(event.target.hasAttribute('data-preview-input'))previewResponse(item)[0]=event.target.value;if(event.target.dataset.previewBlank!==undefined)previewResponse(item)[Number(event.target.dataset.previewBlank)]=event.target.value;});
document.addEventListener('submit',event=>{const form=event.target;if(!form.hasAttribute('data-target-form'))return;event.preventDefault();const record=recordFor(form.dataset.targetForm);Object.assign(record.targets[Number(form.dataset.index)],Object.fromEntries(new FormData(form)));record.status='review';localEdits.set(`${form.dataset.targetForm}:${step}`,structuredClone(record));render();});

export async function importStudio(form){const values=Object.fromEntries(new FormData(form)),files=[...form.elements.pdf.files];delete values.pdf;batch=[];const inputs=files.length?files:[null];for(const file of inputs){if(file?.size>7000000){toast(`${file.name}: PDF는 7MB 이하로 올려 주세요.`);continue;}const pdfBase64=file?await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);}):null;const result=await api('studio_import',{...values,sourceKind:file?'pdf':'text',...(file?{pdfBase64,documentName:file.name}:{})});if(result)batch.push(...result.drafts);}renderBatch();}
function renderBatch(){const element=document.querySelector('#factory-review');element.hidden=false;element.innerHTML=`<section class="card"><h2>${batch.length}개 Passage Draft</h2><p>지문 경계만 확인하세요. 저장 후 각 Passage에서 문장을 편집합니다.</p>${batch.map((draft,index)=>`<article class="studio-batch"><header><input data-batch-title="${index}" aria-label="Passage 제목" value="${esc(draft.job.title)}"><span>${draft.rows.length}문장</span></header><details><summary>문장 확인</summary>${draft.rows.map((row,n)=>`<p><strong>${n+1}</strong><span>${esc(row.text)}</span><small>${esc(row.translation)}</small></p>`).join('')}</details><label><input type="checkbox" data-batch-confirm="${index}" ${draft.boundaryConfirmed?'checked':''}> 이 Passage 확인</label><span>${draft.saved?'✓ 저장됨':''}</span></article>`).join('')}<button class="button primary" type="button" data-batch-save>모두 Passage로 저장</button></section>`;}
document.addEventListener('change',event=>{if(event.target.dataset.batchConfirm!==undefined)batch[Number(event.target.dataset.batchConfirm)].boundaryConfirmed=event.target.checked;});
document.addEventListener('input',event=>{if(event.target.dataset.batchTitle!==undefined)batch[Number(event.target.dataset.batchTitle)].job.title=event.target.value;});
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button?.hasAttribute('data-batch-save'))return;if(batch.some(draft=>!draft.boundaryConfirmed))return toast('각 Passage를 확인해 주세요.');for(const draft of batch){if(draft.saved)continue;const result=await api('studio_create_draft',{jobId:draft.job.id,title:draft.job.title,rows:draft.rows,boundaryConfirmed:true});if(result)draft.saved=result.passageId;else break;}renderBatch();await refresh();const saved=batch.find(draft=>draft.saved);if(batch.every(draft=>draft.saved)&&saved){toast(`${batch.length}개 Passage를 저장했습니다.`);await openPassage(saved.saved);}});
