import { readyApi } from './api.js';

const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const SESSION_KEY='ready-student-session';
const CACHE_INDEX='ready-passage-cache-v2:';
const state={token:'',student:null,selectedStudent:null,scope:null,passages:[],passage:null,sentences:[],questionSession:null,workbookSession:null,reviewCount:0};
let busyCount=0,toastTimer;

function busy(on,label='잠시만요…'){busyCount=Math.max(0,busyCount+(on?1:-1));$('#busy').hidden=!busyCount;$('#busy span:last-child').textContent=label;}
function toast(message,ms=1900){const node=$('#toast');node.textContent=message;node.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('on'),ms);}
function theme(next){const dark=next==='dark';document.documentElement.classList.toggle('dark',dark);document.body.classList.toggle('dark',dark);localStorage.setItem('ready-theme',next);}
async function call(op,data={},token=state.token,label='잠시만요…'){busy(true,label);try{return await readyApi(op,data,token);}finally{busy(false);}}
function record(op,data={}){readyApi(op,data,state.token).catch(()=>{});}
function clearSession(){localStorage.removeItem(SESSION_KEY);Object.assign(state,{token:'',student:null,scope:null,passages:[],passage:null,sentences:[],questionSession:null,workbookSession:null,reviewCount:0});}
async function safely(job,{auth=true}={}){try{return await job();}catch(error){if(auth&&error.status===401){clearSession();await chooseStudent();}toast(error.message||'요청을 처리하지 못했습니다.',3600);return null;}}
function show(...ids){['student-home','pin-login','student-sets','student-reader','student-questions','student-workbook','student-library'].forEach(id=>$('#'+id).hidden=!ids.includes(id));document.body.classList.toggle('study-mode',ids.includes('student-reader')||ids.includes('student-questions')||ids.includes('student-workbook'));}
function updateStudentNav(){const nav=$('#student-nav');nav.hidden=!state.token;$('#logout').hidden=!state.token;const review=nav.querySelector('[data-student-route="review"]');if(review)review.innerHTML=`오답 복습${state.reviewCount?` <span>${state.reviewCount}</span>`:''}`;}

async function chooseStudent(){const data=await safely(()=>call('list_students',{},'','학생 목록을 불러오는 중…'),{auth:false});if(!data)return;state.selectedStudent=null;show('student-home');updateStudentNav();$('#student-list').innerHTML=data.students.length?data.students.map(student=>`<button class="student-button" type="button" data-student-id="${student.id}" data-student-name="${esc(student.name)}">${esc(student.name)}</button>`).join(''):'<div class="empty">등록된 학생이 없습니다.</div>';}
function openPin(student){state.selectedStudent=student;show('pin-login');$('#pin-student-name').textContent=student.name;$('#student-pin').focus();}
async function login(form){const values=Object.fromEntries(new FormData(form)),data=await safely(()=>call('student_login',{studentId:state.selectedStudent.id,pin:values.pin,remember:values.remember==='on'},'','PIN을 확인하는 중…'),{auth:false});form.reset();$('#student-pin').blur();if(!data)return;state.token=data.session.token;state.student=data.student;if(data.session.remember)localStorage.setItem(SESSION_KEY,JSON.stringify(data.session));else localStorage.removeItem(SESSION_KEY);await loadDashboard();}
async function loadDashboard(){const data=await safely(()=>call('student_bootstrap',{},state.token,'학습 범위를 준비하는 중…'));if(!data)return;state.student=data.student;state.scope=data.scope;state.passages=data.passages;state.reviewCount=Number(data.reviewCount)||0;updateStudentNav();renderScope();}

function hasWorkbook(passage){const identity=`${passage?.title||''} ${passage?.source_label||''}`;return /민병천|NE\s*능률/i.test(identity)&&/(?:Lesson|레슨|제)\s*1|1\s*과/i.test(identity);}
function passageChoice(passage,index){const count=Number(passage.question_count)||0,workbook=hasWorkbook(passage);return `<div class="passage-row"><button class="passage-open" type="button" data-start-passage="${passage.id}"><span><strong>${esc(passage.title)}</strong><small>${passage.source_type==='TEXTBOOK'?'교과서 본문':'모의고사'} · 지문 ${index+1}</small></span><b aria-hidden="true">›</b></button><div class="passage-actions">${workbook?`<button class="passage-workbook" type="button" data-start-workbook="${passage.id}">워크북</button>`:''}<button class="passage-question" type="button" data-start-questions="${passage.id}" ${count?'':`disabled aria-label="${esc(passage.title)} 학습 완료"`}>${count?`${count}문제`:'완료'}</button></div></div>`;}
function scopePassagesHtml(){return `<div class="passage-list">${state.passages.map(passageChoice).join('')}</div>`;}
function renderScope(){state.questionSession=null;state.workbookSession=null;show('student-sets');const content=!state.scope?'<div class="empty scope-empty"><strong>아직 배정된 시험범위가 없습니다.</strong></div>':state.passages.length?scopePassagesHtml():'<div class="empty scope-empty"><strong>아직 배정된 지문이 없습니다.</strong></div>';$('#student-sets').innerHTML=`<div class="home-head"><span>학습할 지문</span><small>${state.scope?`${esc(state.student.school)} · ${esc(state.student.grade)}`:''}</small></div><div class="home-content">${content}</div>`;}

function workbookCurrent(){const session=state.workbookSession,stage=session?.data.stages[session.stageIndex];return {session,stage,item:stage?.items[session.itemIndex]};}
function workbookValues(session,item){return session.responses[item.key]||Array(item.slotCount).fill('');}
function workbookSlotState(result,index){return result?(result.slotResults?.[index]?'correct':'wrong'):'';}
function workbookBlankHtml(item,values,result){let slot=0;return String(item.prompt||'').split(/_{5,}/).map((part,index,all)=>{const copy=esc(part);if(index===all.length-1)return copy;const value=values[slot]||'',expected=result?.answers?.[slot]||'',status=workbookSlotState(result,slot),hint=item.hints?.[slot],input=`<span class="workbook-blank ${status}">${hint?`<small class="workbook-hint">${esc(hint)}</small>`:''}<input type="text" data-workbook-slot="${slot}" value="${esc(value)}" aria-label="빈칸 ${slot+1}${hint?` (${esc(hint)})`:''}" ${result?'disabled':''} autocomplete="off" autocapitalize="off" spellcheck="false">${result&&status==='wrong'?`<small class="workbook-answer">정답: ${esc(expected)}</small>`:''}</span>`;slot+=1;return copy+input;}).join('');}
function workbookChoiceHtml(item,values,result){return esc(item.prompt).replace(/⟦CHOICE:(\d+)⟧/g,(_all,indexText)=>{const index=Number(indexText),status=workbookSlotState(result,index);return `<span class="workbook-choice-group ${status}" role="group" aria-label="선택 ${index+1}">${(item.groups?.[index]||[]).map(option=>`<button type="button" data-workbook-choice-group="${index}" data-workbook-choice-value="${esc(option)}" class="workbook-choice${values[index]===option?' selected':''}" aria-pressed="${values[index]===option}" ${result?'disabled':''}>${esc(option)}</button>`).join('<i>/</i>')}${result&&status==='wrong'?`<small>정답: ${esc(result.answers[index])}</small>`:''}</span>`;});}
function workbookCorrectionHtml(item,values,result){return `<div class="workbook-task-passage" lang="en">${esc(item.prompt)}</div><div class="workbook-correction-list">${Array.from({length:item.pairCount},(_,pair)=>{const wrongIndex=pair*2,correctIndex=wrongIndex+1,status=result?(result.slotResults?.[wrongIndex]&&result.slotResults?.[correctIndex]?'correct':'wrong'):'';return `<div class="workbook-correction-row ${status}"><span>${pair+1}</span><label>어색한 표현<input type="text" data-workbook-slot="${wrongIndex}" value="${esc(values[wrongIndex]||'')}" ${result?'disabled':''} autocomplete="off" autocapitalize="off" spellcheck="false"></label><b aria-hidden="true">→</b><label>바르게 고치기<input type="text" data-workbook-slot="${correctIndex}" value="${esc(values[correctIndex]||'')}" ${result?'disabled':''} autocomplete="off" autocapitalize="off" spellcheck="false"></label>${result&&status==='wrong'?`<small>${esc(result.answers[wrongIndex])} → ${esc(result.answers[correctIndex])}</small>`:''}</div>`;}).join('')}</div>`;}
function workbookOrderSelections(session,item){session.orderSelections??={};return session.orderSelections[item.key]??=Array.from({length:item.groups?.length||0},()=>[]);}
function workbookOrderHtml(item,values,result,session){const selections=workbookOrderSelections(session,item);return esc(item.prompt).replace(/⟦ORDER:(\d+)⟧/g,(_all,indexText)=>{const index=Number(indexText),group=item.groups?.[index]||[],chosen=selections[index]||[],chosenSet=new Set(chosen),status=workbookSlotState(result,index);return `<span class="workbook-order-group ${status}"><span class="workbook-order-built">${chosen.length?chosen.map(chipIndex=>`<button type="button" data-workbook-order-remove="${index}:${chipIndex}" ${result?'disabled':''}>${esc(group[chipIndex])}</button>`).join(' '):'<em>단어를 순서대로 누르세요</em>'}</span><span class="workbook-order-bank">${group.map((word,chipIndex)=>`<button type="button" data-workbook-order-add="${index}:${chipIndex}" ${chosenSet.has(chipIndex)||result?'disabled':''}>${esc(word)}</button>`).join('')}</span>${result&&status==='wrong'?`<small>정답: ${esc(result.answers[index])}</small>`:''}</span>`;});}
function workbookTaskHtml(item,values,result,session){if(item.kind==='choice_groups')return `<div class="workbook-prompt choice-task" lang="en">${workbookChoiceHtml(item,values,result)}</div>`;if(item.kind==='correction_pairs')return workbookCorrectionHtml(item,values,result);if(item.kind==='reorder_groups')return `<div class="workbook-prompt order-task" lang="en">${workbookOrderHtml(item,values,result,session)}</div>`;return `<div class="workbook-prompt" lang="${item.kind==='blank_input'?'ko':'en'}">${workbookBlankHtml(item,values,result)}</div>`;}
function workbookTabsHtml(session){return session.data.stages.map((stage,index)=>`<button type="button" data-workbook-stage="${index}" class="${index===session.stageIndex?'active':''}" ${stage.locked?'disabled aria-disabled="true"':''}><span>${stage.stage}단계${stage.locked?' · 준비 중':''}</span><b>${stage.locked?'잠김':`${stage.completed}/${stage.total}`}</b></button>`).join('');}
function renderWorkbook(){const {session,stage,item}=workbookCurrent();if(!session||!stage||!item)return renderScope();const values=workbookValues(session,item),result=session.results[item.key],ready=values.length===item.slotCount&&values.every(value=>String(value).trim()),lastItem=session.itemIndex===stage.items.length-1,lastStage=session.stageIndex===session.data.stages.length-1,nextLabel=lastItem?(lastStage?'학습 목록':'다음 단계'):'다음 문제';show('student-workbook');$('#student-workbook').innerHTML=`<button class="study-back" type="button" data-exit-workbook aria-label="학습 목록으로"><span aria-hidden="true">‹</span></button><div class="workbook-layout"><header class="workbook-head"><p class="eyebrow">READY · WORKBOOK</p><h1>${esc(session.data.title)}</h1><p>직접 쓰고 바로 확인하는 문장 연습입니다.</p></header><nav class="workbook-tabs" aria-label="워크북 단계">${workbookTabsHtml(session)}</nav><section class="workbook-card"><div class="workbook-meta"><span>${stage.title}</span><b>${session.itemIndex+1} / ${stage.total}</b></div><p class="workbook-instruction">${esc(stage.instruction)}</p>${item.source?`<blockquote lang="${item.kind==='blank_input'?'en':'ko'}">${esc(item.source)}</blockquote>`:''}${workbookTaskHtml(item,values,result,session)}${result?`<div class="workbook-feedback ${result.correct?'correct':'wrong'}"><strong>${result.correct?'정답입니다.':'표시된 부분만 고쳐 보세요.'}</strong><span>${result.correct?'Enter를 누르거나 다음 문장으로 넘어가세요.':'맞은 부분은 유지되고, 틀린 부분만 다시 풀 수 있습니다.'}</span></div>`:''}<div class="workbook-actions">${result&&!result.correct?'<button class="button primary" type="button" data-workbook-retry>틀린 부분 다시 풀기</button>':result?`<button class="button primary" type="button" data-workbook-next>${nextLabel}</button>`:`<button class="button primary" type="button" data-submit-workbook ${ready?'':'disabled'}>채점하기</button>`}</div></section><div class="workbook-nav"><button class="button quiet" type="button" data-workbook-prev ${session.itemIndex===0?'disabled':''}>← 이전</button><button class="button quiet" type="button" data-exit-workbook>학습 목록</button></div></div>`;}
async function openWorkbook(passageId){if(!state.scope)return;const data=await safely(()=>call('student_workbook',{examId:state.scope.id,passageId},state.token,'워크북을 준비하는 중…'));if(!data)return;const available=data.stages.map((stage,index)=>({...stage,index})).filter(stage=>!stage.locked&&stage.items.length),next=available.find(stage=>stage.completed<stage.total)||available[0];if(!next){toast('현재 풀 수 있는 워크북 단계가 없습니다.');return;}const stageIndex=next.index,stage=data.stages[stageIndex],itemIndex=Math.max(0,stage.items.findIndex(item=>!item.completed));state.workbookSession={data,passageId,stageIndex,itemIndex,responses:{},results:{},orderSelections:{}};renderWorkbook();}
function updateWorkbookSlot(index,value){const {session,item}=workbookCurrent();if(!session||!item||session.results[item.key])return;const values=[...(session.responses[item.key]||Array(item.slotCount).fill(''))];values[index]=value;session.responses[item.key]=values;const submit=$('[data-submit-workbook]');if(submit)submit.disabled=!values.every(item=>String(item).trim());}
function chooseWorkbookOption(group,value){updateWorkbookSlot(group,value);renderWorkbook();}
function changeWorkbookOrder(group,chipIndex,remove=false){const {session,item}=workbookCurrent();if(!session||!item||session.results[item.key])return;const selections=workbookOrderSelections(session,item),current=[...(selections[group]||[])],position=current.indexOf(chipIndex);if(remove&&position>=0)current.splice(position,1);else if(!remove&&position<0)current.push(chipIndex);selections[group]=current;const words=(item.groups?.[group]||[]);updateWorkbookSlot(group,current.map(index=>words[index]).join(' '));renderWorkbook();}
async function submitWorkbook(){const {session,item}=workbookCurrent();if(!session||!item||session.results[item.key])return;const responses=session.responses[item.key]||[];if(responses.length!==item.slotCount||responses.some(value=>!String(value).trim()))return;const data=await safely(()=>call('submit_workbook_attempt',{examId:state.scope.id,passageId:session.passageId,itemKey:item.key,responses},state.token,'답을 채점하는 중…'));if(!data)return;session.results[item.key]={correct:data.correct,answers:data.answers,slotResults:data.slotResults};item.completed=data.correct;if(data.correct){const stage=session.data.stages[session.stageIndex];stage.completed=stage.items.filter(candidate=>candidate.completed).length;}renderWorkbook();}
function retryWorkbook(){const {session,item}=workbookCurrent();if(!session||!item)return;const result=session.results[item.key],previous=session.responses[item.key]||Array(item.slotCount).fill('');let next=previous.map((value,index)=>result?.slotResults?.[index]?value:'');if(item.kind==='correction_pairs')for(let pair=0;pair<item.pairCount;pair+=1){const left=pair*2,right=left+1;if(!result?.slotResults?.[left]||!result?.slotResults?.[right])next[left]=next[right]='';}if(item.kind==='reorder_groups'){const selections=workbookOrderSelections(session,item);result?.slotResults?.forEach((correct,index)=>{if(!correct)selections[index]=[];});}session.responses[item.key]=next;delete session.results[item.key];renderWorkbook();requestAnimationFrame(()=>document.querySelector('[data-workbook-slot][value=""]')?.focus());}
function moveWorkbook(delta){const {session,stage}=workbookCurrent();if(!session||!stage)return;const next=session.itemIndex+delta;if(next>=0&&next<stage.items.length){session.itemIndex=next;return renderWorkbook();}if(next>=stage.items.length){const nextStage=session.data.stages.findIndex((candidate,index)=>index>session.stageIndex&&!candidate.locked&&candidate.items.length);if(nextStage>=0){session.stageIndex=nextStage;session.itemIndex=0;return renderWorkbook();}return renderScope();}}
function setWorkbookStage(index){const session=state.workbookSession,stage=session?.data.stages[index];if(!session||!stage||stage.locked)return;session.stageIndex=index;session.itemIndex=Math.max(0,stage.items.findIndex(item=>!item.completed));renderWorkbook();}

function cleanDisplayText(value){return String(value||'').replace(/^\s*(?:[※]\s*)?다음\s*(?:글|대화)(?:을|를)\s*읽고\s*(?:다음\s*)?물음에\s*답하시오\s*[.!?]?\s*/u,'').replace(/\s+/g,' ').trim();}
function plainPassage(){return state.sentences.map(sentence=>esc(cleanDisplayText(sentence.text))).filter(Boolean).join(' ');}
function readerUnits(){const text=state.sentences.map(sentence=>cleanDisplayText(sentence.text)).filter(Boolean).join(' ');if(!text)return [];try{return [...new Intl.Segmenter('en',{granularity:'sentence'}).segment(text)].map(item=>item.segment.trim()).filter(Boolean);}catch{return text.split(/(?<=[.!?])\s+(?=[A-Z“"'])/).filter(Boolean);}}
function readerParagraphs(units){const paragraphs=[];let current=[];for(const unit of units){const length=current.join(' ').length;if(current.length&&length+unit.length>430){paragraphs.push(current.join(' '));current=[];}current.push(unit);}if(current.length)paragraphs.push(current.join(' '));return paragraphs;}
function renderReader(){const units=readerUnits(),lead=units.shift()||'',paragraphs=readerParagraphs(units);show('student-reader');$('#student-reader').innerHTML=`<button class="study-back" type="button" data-exit-study aria-label="학습 목록으로"><span aria-hidden="true">‹</span></button><div class="reader-shell reader-document"><p class="eyebrow">TEXTBOOK · READER</p><h1>${esc(state.passage.title)}</h1>${lead?`<p class="reader-lede">${esc(lead)}</p>`:''}<article class="reader-prose">${paragraphs.length?paragraphs.map(paragraph=>`<p>${esc(paragraph)}</p>`).join(''):`<p>${plainPassage()}</p>`}</article></div>`;}
function cacheIndexKey(passageId){return `${CACHE_INDEX}${state.student?.id}:${passageId}`;}
function cachedPassage(passageId){try{const pointer=JSON.parse(localStorage.getItem(cacheIndexKey(passageId))||'null');return pointer?.key?JSON.parse(localStorage.getItem(pointer.key)||'null'):null;}catch{return null;}}
function cachePassage(data){try{const revision=[data.passage.id,data.passage.updated_at||'current'].join(':'),key=`ready-passage-cache-v2:${state.student.id}:${revision}`;localStorage.setItem(key,JSON.stringify(data));localStorage.setItem(cacheIndexKey(data.passage.id),JSON.stringify({key,revision}));}catch{/* disposable acceleration only */}}
function applyPassage(data){Object.assign(state,{passage:data.passage,sentences:data.sentences||[]});}
async function openPassageStudy(passageId){if(!state.scope)return;state.questionSession=null;const cached=cachedPassage(passageId);if(cached){applyPassage(cached);renderReader();}const data=await safely(()=>cached?readyApi('student_passage',{examId:state.scope.id,passageId},state.token):call('student_passage',{examId:state.scope.id,passageId},state.token,'지문을 준비하는 중…'));if(!data)return;applyPassage(data);renderReader();cachePassage(data);localStorage.setItem(`ready-last-passage:${state.student.id}:${state.scope.id}`,passageId);}

function interactionClass(selected,correct,submitted){return `${selected?' selected':''}${submitted&&correct?' correct':''}${submitted&&selected&&!correct?' wrong':''}`;}
function segmentHtml(segment,context={}){const kind=['blank','underline','label','choice','emphasis','target'].includes(segment?.kind)?segment.kind:'text';if(kind==='target'){const pointed=(context.question?.targetRanges||[]).some(target=>target.label===segment.label);return pointed?`<span class="passage-pointer"><b>${esc(segment.label)}</b>${esc(segment.text)}</span>`:esc(segment.text);}return `<span class="question-segment ${kind}"${segment?.label?` data-label="${esc(segment.label)}"`:''}>${kind==='blank'&&!segment.text?'________':esc(segment?.text)}</span>`;}
function segmentJoinSpace(previous,current){const before=String(previous?.text||''),after=String(current?.text||'');return /[A-Za-z0-9),.;:!?…”’]$/.test(before)&&/^[A-Za-z0-9(“‘]/.test(after)?' ':'';}
function blockHtml(block,context){const kind=['heading','paragraph','given','group','bullet','note','image'].includes(block?.kind)?block.kind:'paragraph';if(kind==='image')return block.url?`<figure class="question-image"><img src="${esc(block.url)}" alt="${esc(block.alt||'문제 자료')}">${block.caption?`<figcaption>${esc(block.caption)}</figcaption>`:''}</figure>`:'';const content=block.segments?.length?block.segments.map((segment,index)=>`${index?segmentJoinSpace(block.segments[index-1],segment):''}${segmentHtml(segment,context)}`).join(''):esc(block.text);if(kind==='bullet')return `<li>${content}</li>`;return `<section class="question-block ${kind}">${block.label?`<strong>${esc(block.label)}</strong>`:''}<span>${content}</span></section>`;}
function splitPassageFootnote(value){const text=String(value||''),match=text.match(/^(.*?)(\*{1,2}[A-Za-z][\s\S]*)$/);return match?{body:match[1].trimEnd(),note:match[2].trim()}:{body:text,note:''};}
function passageTextHtml(value){const {body,note}=splitPassageFootnote(value);return `${esc(body)}${note?`<small class="question-footnote">${esc(note)}</small>`:''}`;}
function inlineOptionPassageHtml(question,result,inlineSelected){const split=splitPassageFootnote(question.variantText||''),text=split.body,pattern=/([ⓐ-ⓩ]|\([A-H]\))\s*\[([^\]]+)\]/g;let html='',cursor=0,groupIndex=0,match;while((match=pattern.exec(text))){html+=esc(text.slice(cursor,match.index));const group=question.inlineGroups[groupIndex],correctIndex=result?.answer?.[groupIndex];html+=`<span class="inline-option-group"><b>${esc(group?.label||match[1])}</b>${(group?.options||match[2].split('/').map(value=>value.trim())).map((option,optionIndex)=>{const selected=inlineSelected?.[groupIndex]===optionIndex,correct=correctIndex===optionIndex;return `<button class="inline-answer option${interactionClass(selected,correct,!!result)}" type="button" data-inline-group="${groupIndex}" data-inline-option="${optionIndex}" aria-pressed="${selected}">${esc(option)}</button>`;}).join('<i>/</i>')}</span>`;cursor=pattern.lastIndex;groupIndex+=1;}return `<p>${html}${esc(text.slice(cursor))}${split.note?`<small class="question-footnote">${esc(split.note)}</small>`:''}</p>`;}
function inlineTargetPassageHtml(question,result,selected){const split=splitPassageFootnote(question.variantText||question.passageText||''),text=split.body;let cursor=0,html='';for(const [index,target] of question.targetRanges.entries()){const pattern=new RegExp(`${String(target.label).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*${String(target.text).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}`),match=pattern.exec(text.slice(cursor));if(!match)continue;const start=cursor+match.index,chosen=selected.includes(index),correct=result?.answer?.includes(index);html+=esc(text.slice(cursor,start));html+=`<button class="inline-answer target${interactionClass(chosen,correct,!!result)}" type="button" data-target-choice="${index}" aria-pressed="${chosen}"><span>${esc(target.label)}</span>${esc(target.text)}</button>`;cursor=start+match[0].length;}return `<p>${html}${esc(text.slice(cursor))}${split.note?`<small class="question-footnote">${esc(split.note)}</small>`:''}</p>`;}
function implicationPassageHtml(question){const text=question.variantText||question.passageText||'',split=splitPassageFootnote(text),match=question.prompt.match(/밑줄 친\s+(\([A-H]\).+?)(?=[가이]\s*의미)/),target=match?.[1],index=target?split.body.indexOf(target):-1;if(index<0)return `<p>${passageTextHtml(text)}</p>`;return `<p>${esc(split.body.slice(0,index))}<span class="question-segment underline">${esc(target)}</span>${esc(split.body.slice(index+target.length))}${split.note?`<small class="question-footnote">${esc(split.note)}</small>`:''}</p>`;}
function canonicalHasOption(canonical,option){const escaped=String(option).replace(/[.*+?^${}()|[\]\\]/g,'\\$&').replace(/\s+/g,'\\s+');return new RegExp(`(^|[^A-Za-z])${escaped}([^A-Za-z]|$)`,'i').test(canonical);}
function canonicalOption(canonical,options){return [...options].filter(option=>canonicalHasOption(canonical,option)).sort((a,b)=>b.length-a.length)[0]||options[0];}
function resolvedSetPassageText(question){const canonical=question.passageText||'',raw=question.variantText||canonical;return raw.replace(/([ⓐ-ⓩ]|\([A-H]\))\s*\[([^\]]+)\]/g,(_match,label,value)=>{const options=value.split('/').map(option=>option.trim()),resolved=canonicalOption(canonical,options);return `${label}${resolved}`;}).replace(/\s+/g,' ').trim();}
function labelNeedleIndex(text,needles,from=0){const lower=text.toLocaleLowerCase(),ordered=[...new Set(needles.filter(Boolean))].sort((a,b)=>b.length-a.length);for(const needle of ordered){const escaped=String(needle).replace(/[.*+?^${}()|[\]\\]/g,'\\$&').replace(/\s+/g,'\\s+'),match=new RegExp(`(^|[^A-Za-z])(${escaped})(?=[^A-Za-z]|$)`,'i').exec(text.slice(from));if(match)return from+match.index+match[1].length;}for(const needle of ordered){const index=lower.indexOf(String(needle).toLocaleLowerCase(),from);if(index>=0)return index;}return -1;}
function replaceNeedle(value,needles,replacement,from=0){const ordered=[...new Set(needles.filter(Boolean))].sort((a,b)=>b.length-a.length);for(const needle of ordered){const escaped=String(needle).replace(/[.*+?^${}()|[\]\\]/g,'\\$&').replace(/\s+/g,'\\s+'),match=new RegExp(`(^|[^A-Za-z])(${escaped})(?=[^A-Za-z]|$)`,'i').exec(value.slice(from));if(!match)continue;const index=from+match.index+match[1].length;return {text:`${value.slice(0,index)}${replacement}${value.slice(index+match[2].length)}`,index};}const lower=value.toLocaleLowerCase();for(const needle of ordered){const index=lower.indexOf(String(needle).toLocaleLowerCase(),from);if(index>=0)return {text:`${value.slice(0,index)}${replacement}${value.slice(index+String(needle).length)}`,index};}return {text:value,index:-1};}
function maskBlank(value,question){if(question.skill!=='blank')return value;const labels=[...new Set(String(question.variantText||'').match(/[㉠-㉭]/g)||[])];let text=value;for(const [order,label] of labels.entries()){if(text.includes(label))continue;const candidates=(question.choices||[]).filter(choice=>canonicalHasOption(text,choice)).sort((a,b)=>b.length-a.length),answer=candidates[0];if(!answer)continue;const replaced=replaceNeedle(text,[answer],`${label}${'_'.repeat(Math.max(22,Math.min(54,String(answer).length*2)))}`);text=replaced.text;}return text;}
function worksheetPassageText(question){return String(question.variantText||question.passageText||'').replace(/([ⓐ-ⓩ]|\([A-H]\))\s*\[([^\]]+)\]/g,(_match,label,options)=>`${label}${options.split('/').map(value=>value.trim()).join(' / ')}`).replace(/\s+/g,' ').trim();}
function activeQuestionLabels(question){const labels=referencedLabels(question.prompt);if(question.skill==='order')for(const label of String((question.choices||[]).join(' ')).match(/\([A-H]\)/g)||[])labels.add(label);for(const item of question.targetRanges||[])if(item.label)labels.add(item.label);for(const item of question.inlineGroups||[])if(item.label)labels.add(item.label);return labels;}
function englishWordSpans(value){return [...String(value||'').matchAll(/[A-Za-z]+(?:[’'][A-Za-z]+)?/g)].map(match=>({word:match[0].toLowerCase(),start:match.index,end:(match.index||0)+match[0].length}));}
function matchingTokenSequence(haystack,needles,from=0,last=false){if(!needles.length)return null;const spans=englishWordSpans(haystack);let found=null;for(let index=0;index<=spans.length-needles.length;index+=1){if(spans[index].start<from)continue;if(needles.every((word,offset)=>spans[index+offset].word===word)){found={start:spans[index].start,end:spans[index+needles.length-1].end};if(!last)return found;}}return found;}
function canonicalGap(value,start,end,canonical){const before=englishWordSpans(value.slice(0,start)).map(item=>item.word),after=englishWordSpans(value.slice(end)).map(item=>item.word);for(let size=7;size>=2;size-=1){const leftWords=before.slice(-size),rightWords=after.slice(0,size);if(leftWords.length<2||rightWords.length<2)continue;const left=matchingTokenSequence(canonical,leftWords,0,true);if(!left)continue;const right=matchingTokenSequence(canonical,rightWords,left.end);if(!right||right.start<left.end)continue;return canonical.slice(left.end,right.start).replace(/^\s*[.!?,;:]\s*|\s*[.!?,;:]\s*$/g,'').trim();}return '';}
function restoreInactiveQuestionDevices(value,question){const canonical=String(question.passageText||''),active=activeQuestionLabels(question);let text=String(value||'');const blankPattern=/\([A-H]\)\s*[_＿]{3,}/g;for(const match of [...text.matchAll(blankPattern)].reverse()){const label=match[0].match(/\([A-H]\)/)?.[0];if(!label||active.has(label))continue;const start=match.index||0,end=start+match[0].length,replacement=canonicalGap(text,start,end,canonical);if(replacement)text=`${text.slice(0,start)}${replacement}${text.slice(end)}`;}const koreanPattern=/[ⓐ-ⓩ]\s*[^A-Za-z]*[가-힣][^A-Za-z]*?(?=\s+[A-Za-z])/g;for(const match of [...text.matchAll(koreanPattern)].reverse()){const label=match[0].match(/[ⓐ-ⓩ]/)?.[0];if(!label||active.has(label))continue;const start=match.index||0,end=start+match[0].length,replacement=canonicalGap(text,start,end,canonical);if(replacement)text=`${text.slice(0,start)}${replacement} ${text.slice(end)}`;}return text;}
function cleanQuestionApparatus(value,question){const canonical=question.passageText||'',active=activeQuestionLabels(question);let text=restoreInactiveQuestionDevices(value,question);text=text.replace(/([ⓐ-ⓩ]|\([A-H]\))\s*\[([^\]]+)\]/g,(_all,label,raw)=>{const options=raw.split('/').map(item=>item.trim()),word=canonicalOption(canonical,options);return `${active.has(label)?label:''}${word}`;});text=text.replace(/[ⓐ-ⓩ]|\([A-H]\)/g,label=>active.has(label)?label:'');const taskStart=text.search(/\s+\(\d+\)\s*(?:What|Why|How|Where|When|Who|Which)\b/i);if(taskStart>0)text=text.slice(0,taskStart);const summary=String(question.summaryText||'').replace(/\s+/g,' ').trim();if(summary){const seed=(summary.match(/[A-Za-z]+(?:[’'][A-Za-z]+)?/g)||[]).slice(0,7).join(' '),index=seed?labelNeedleIndex(text,[seed]):-1;if(index>0)text=text.slice(0,index);}return text.replace(/\s+/g,' ').trim();}
function questionAnchorTexts(question){return [...(question.targetRanges||[]).map(item=>item.canonicalText||item.text),...(question.inlineGroups||[]).flatMap(item=>item.options||[])].filter(Boolean);}
function canonicalQuestionWindow(question){const canonical=String(question.passageText||''),anchors=questionAnchorTexts(question);if(!canonical||!anchors.length)return '';const chunks=canonical.match(/[^.!?]+(?:[.!?]+|$)/g)?.map(item=>item.trim()).filter(Boolean)||[canonical];const hits=chunks.map((chunk,index)=>anchors.some(anchor=>canonicalHasOption(chunk,anchor))?index:-1).filter(index=>index>=0);if(!hits.length)return '';return chunks.slice(Math.max(0,Math.min(...hits)-1),Math.min(chunks.length,Math.max(...hits)+2)).join(' ');}
function questionBasePassage(question){const canonical=String(question.passageText||''),anchors=questionAnchorTexts(question);let text=question.setText||question.variantText||canonical;if(question.responseType==='written')text=question.setText||question.variantText||canonical;else if(question.variantMode==='authored_variant')text=question.setText||question.variantText||canonical;else if(anchors.length&&anchors.every(anchor=>canonicalHasOption(canonical,anchor))){const window=canonicalQuestionWindow(question);text=window||question.setText||canonical;}else if(anchors.length&&!anchors.some(anchor=>canonicalHasOption(text,anchor))){const window=canonicalQuestionWindow(question);if(window)text=window;}text=cleanDisplayText(text);text=cleanQuestionApparatus(text,question);text=maskBlank(text,question);return String(text).replace(/\s+/g,' ').trim();}
function applyAlternativeOverlay(value,question){let text=value,cursor=0;for(const group of question.inlineGroups||[]){const options=group.options||[],preferred=canonicalOption(question.passageText||value,options),expression=`${group.label}${options.join(' / ')}`,replaced=replaceNeedle(text,[preferred,...options],expression,cursor);if(replaced.index<0)continue;text=replaced.text;cursor=replaced.index+expression.length;}return text;}
function applyTargetOverlay(value,question){let text=value,cursor=0;for(const target of question.targetRanges||[]){if(!target.label||!target.text)continue;const expression=`${target.label}${target.text}`,labelPattern=String(target.label).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),textPattern=String(target.text).replace(/[.*+?^${}()|[\]\\]/g,'\\$&').replace(/\s+/g,'\\s+'),existing=new RegExp(`${labelPattern}\\s*${textPattern}`,'i').exec(text.slice(cursor));if(existing){const index=cursor+existing.index;text=`${text.slice(0,index)}${expression}${text.slice(index+existing[0].length)}`;cursor=index+expression.length;continue;}const anchor=target.canonicalText||target.text,replaced=replaceNeedle(text,[anchor],expression,cursor);if(replaced.index<0)continue;text=replaced.text;cursor=replaced.index+expression.length;}return text;}
function structuralMarkerPositions(question,value){const groupLabels=new Set((question.inlineGroups||[]).map(group=>group.label)),raw=resolvedSetPassageText(question),matches=[...raw.matchAll(/\([A-H]\)/g)].filter(match=>!groupLabels.has(match[0])),positions=[];for(const [order,match] of matches.entries()){const next=matches[order+1]?.index??raw.length,tail=raw.slice((match.index||0)+match[0].length,next).replace(/[ⓐ-ⓩ㉠-㉭]/g,'').replace(/_{4,}/g,' ').trim(),words=tail.match(/[A-Za-z]+(?:[’'][A-Za-z]+)?/g)||[];let index=-1;for(let count=Math.min(10,words.length);count>=2&&index<0;count-=1)index=labelNeedleIndex(value,[words.slice(0,count).join(' ')]);if(index>=0)positions.push({index,label:match[0]});}return positions.sort((a,b)=>b.index-a.index);}
function applyStructuralOverlay(value,question){if(question.skill!=='insertion')return value;let text=value;for(const marker of structuralMarkerPositions(question,text))text=`${text.slice(0,marker.index)}${marker.label} ${text.slice(marker.index)}`;return text;}
function currentQuestionPassage(question){if(question.skill==='implication'&&question.variantText)return worksheetPassageText(question);let text=questionBasePassage(question);text=applyAlternativeOverlay(text,question);text=applyTargetOverlay(text,question);text=applyStructuralOverlay(text,question);return text.replace(/\s+/g,' ').trim();}
function referencedLabels(prompt){const labels=new Set(String(prompt||'').match(/[ⓐ-ⓩ㉠-㉭]|\([A-H]\)/g)||[]);for(const match of String(prompt||'').matchAll(/\(([A-H])\)\s*[~～-]\s*\(([A-H])\)/g)){for(let code=match[1].charCodeAt(0);code<=match[2].charCodeAt(0);code+=1)labels.add(`(${String.fromCharCode(code)})`);}for(const match of String(prompt||'').matchAll(/([ⓐ-ⓩ])\s*[~～-]\s*([ⓐ-ⓩ])/g)){for(let code=match[1].codePointAt(0);code<=match[2].codePointAt(0);code+=1)labels.add(String.fromCodePoint(code));}return labels;}
function pointerRanges(question,text){const specs=[],labels=referencedLabels(question.prompt);for(const target of question.targetRanges||[])specs.push({label:target.label,needle:`${target.label}${target.text}`});for(const group of question.inlineGroups||[])specs.push({label:group.label,needle:`${group.label}${(group.options||[]).join(' / ')}`});const implication=String(question.prompt||'').match(/밑줄 친\s+(\([A-H]\).+?)(?=[가이]\s*의미)/)?.[1];if(implication)specs.push({label:implication.slice(0,3),needle:implication});for(const label of labels)if(!specs.some(spec=>spec.label===label)){const start=text.indexOf(label),blank=start>=0?text.slice(start).match(new RegExp(`^${label}[＿_]{4,}`))?.[0]:'';specs.push({label,needle:blank||label});}const ranges=[];for(const spec of specs.sort((a,b)=>b.needle.length-a.needle.length)){let start=text.indexOf(spec.needle);while(start>=0&&ranges.some(range=>start<range.end&&start+spec.needle.length>range.start))start=text.indexOf(spec.needle,start+1);if(start>=0)ranges.push({start,end:start+spec.needle.length,label:spec.label});}return ranges.sort((a,b)=>a.start-b.start);}
function pointedPassageHtml(question,value){const split=splitPassageFootnote(value),ranges=pointerRanges(question,split.body);let cursor=0,html='';for(const range of ranges){html+=esc(split.body.slice(cursor,range.start));const slice=split.body.slice(range.start,range.end),blank=slice.match(/^([㉠-㉭])[_＿]{4,}$/);html+=blank?`<span class="passage-blank"><b>${esc(blank[1])}</b><i aria-hidden="true"></i></span>`:`<span class="passage-pointer">${esc(slice)}</span>`;cursor=range.end;}html+=esc(split.body.slice(cursor));return `<p>${html}${split.note?`<small class="question-footnote">${esc(split.note)}</small>`:''}</p>`;}
function inactiveVariantText(question){const canonical=question.passageText||'',skill=question.skill||'';if(['content','title','topic','purpose','emotion','comprehension','summary'].includes(skill))return canonical;let text=question.variantText||canonical;if(question.interaction!=='inline_options'){text=text.replace(/([ⓐ-ⓩ]|\([A-H]\))\s*\[([^\]]+)\]/g,(_match,_label,raw)=>{const options=raw.split('/').map(value=>value.trim());return options.find(option=>canonicalHasOption(canonical,option))||options[0];});text=text.replace(/[ⓐ-ⓩ]/g,'');}if(skill!=='insertion'&&skill!=='implication')text=text.replace(/\s*\([A-H]\)\s*/g,' ');return text.replace(/\s+/g,' ').trim();}
function insertionPassageHtml(question,result,selected){const text=inactiveVariantText(question);let cursor=0,html='';for(const match of text.matchAll(/\(([A-H])\)/g)){html+=esc(text.slice(cursor,match.index));const label=`(${match[1]})`,index=question.choices.indexOf(label),chosen=selected.includes(index),correct=result?.answer?.includes(index);html+=`<button class="inline-answer position${interactionClass(chosen,correct,!!result)}" type="button" data-position-choice="${index}" aria-pressed="${chosen}" aria-label="삽입 위치 ${esc(label)}">${esc(label)}</button>`;cursor=match.index+match[0].length;}return `<p>${html}${esc(text.slice(cursor))}</p>`;}
function explicitPassageHtml(question,result,selected){const spec=question.renderSpec||{},passage=spec.passage||{},context={question,result,selected},source=passage.source,isolated=question.responseType==='written'||question.skill==='summary';if(source==='blocks'&&!isolated)return (spec.blocks?.length?spec.blocks:question.contentBlocks||[]).map(block=>blockHtml(block,context)).join('');if(source==='segments'&&!isolated)return `<p>${(question.variantSegments||[]).map((segment,index,all)=>`${index?segmentJoinSpace(all[index-1],segment):''}${segmentHtml(segment,context)}`).join('')}</p>`;const annotations=Array.isArray(passage.annotations)?passage.annotations:[];if(annotations.length)question={...question,targetRanges:annotations.filter(item=>item.kind==='target'||item.kind==='underline').map(item=>({label:item.label,text:item.text,canonicalText:item.canonicalText||item.text}))};return pointedPassageHtml(question,currentQuestionPassage(question));}
function questionPassageHtml(question,result,selected){if(question.renderSpec&&!question.renderSpec.legacyAdapter)return explicitPassageHtml(question,result,selected);const context={question,result,selected},deviceSkills=new Set(['grammar','vocabulary','blank','order','insertion','written']);if(Array.isArray(question.contentBlocks)&&question.contentBlocks.length&&!deviceSkills.has(question.skill)&&question.responseType!=='written')return question.contentBlocks.map(block=>blockHtml(block,context)).join('');return pointedPassageHtml(question,currentQuestionPassage(question));}
function normalizedChoice(value){return String(value||'').normalize('NFKC').toLowerCase().replace(/[^a-z0-9]+/g,'');}
function combinationChoiceParts(question,text){const groups=question.inlineGroups||[],expected=normalizedChoice(text);if(groups.length<2||!expected)return null;function visit(index,parts){if(index===groups.length)return normalizedChoice(parts.join(' '))===expected?parts:null;for(const option of groups[index].options||[]){const found=visit(index+1,[...parts,option]);if(found)return found;}return null;}return visit(0,[]);}
function choiceCopyHtml(question,text,index){const parts=question.choiceParts?.[index]||combinationChoiceParts(question,text);return parts?parts.map(part=>`<span>${esc(part)}</span>`).join('<i class="choice-separator" aria-hidden="true">−</i>'):esc(text);}
function questionChoiceHtml(question,text,index,result,selected,markState){const mark=['①','②','③','④','⑤','⑥','⑦','⑧'][index],correct=!!result&&(result.answer?.includes(index)||(result.correct&&selected)),wrong=!!result&&!correct&&selected,state=!result&&(markState==='candidate'||markState==='eliminated')?` ${markState}`:'';return `<div class="question-choice${state} ${selected?'selected':''} ${correct?'correct':''} ${wrong?'wrong':''}" role="${question.multiSelect?'checkbox':'radio'}" aria-checked="${selected}" tabindex="${result?'-1':'0'}" data-question-choice="${index}" data-choice-mark="${esc(markState||'neutral')}"><span class="question-choice-mark">${mark}</span><span class="question-choice-copy">${choiceCopyHtml(question,text,index)}</span></div>`;}
function writingGuideHtml(guide){if(!guide)return '';const task=guide.taskText?`<section class="writing-target"><strong>영작할 우리말</strong><p>${esc(guide.taskText)}</p></section>`:'',conditions=(guide.conditions||[]).length?`<section class="writing-conditions"><strong>조건</strong><ul>${guide.conditions.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></section>`:'',bank=(guide.wordBank||[]).length?`<section class="writing-bank"><strong>사용할 말</strong><div>${guide.wordBank.map(item=>`<span>${esc(item)}</span>`).join('')}</div></section>`:'';return `${task}${conditions}${bank}`;}
function writtenSlotsHtml(slots,values,result,placeholder='답을 입력하세요'){return `<div class="written-slot-list">${slots.map((slot,index)=>{const hint=slot.placeholder||(slot.wordCount?`${slot.wordCount}단어`:placeholder);return `<label><span>${esc(slot.label||`답 ${index+1}`)}</span><input type="text" data-written-slot="${index}" value="${esc(values[index]||'')}" placeholder="${esc(hint)}" ${result?'disabled':''} autocomplete="off" spellcheck="false"></label>`;}).join('')}</div>`;}
function responseArea(question,result,selected,choiceMarks=[]){if(question.responseType==='written'){const values=Array.isArray(selected)?selected:[],slots=question.responseSlots?.length?question.responseSlots:[{label:'답'}],guide=question.writingGuide,targets=guide?.targets||[];if(guide?.kind==='correction'&&targets.length===slots.length)return `<section class="written-workspace correction">${writingGuideHtml(guide)}${targets.map((target,index)=>`<label><span class="correction-source"><b>${esc(target.label)}</b><em>${esc(target.text)}</em></span><i aria-hidden="true">→</i><span class="correction-answer"><small>${esc(slots[index]?.label||`답 ${index+1}`)}</small><input type="text" data-written-slot="${index}" value="${esc(values[index]||'')}" placeholder="고친 말만 입력" ${result?'disabled':''} autocomplete="off" spellcheck="false"></span></label>`).join('')}</section>`;if(guide?.kind==='multi-correction')return `<section class="written-workspace multi-correction">${writingGuideHtml(guide)}<div class="correction-reference">${targets.map(target=>`<span><b>${esc(target.label)}</b>${esc(target.text)}</span>`).join('')}</div>${writtenSlotsHtml(slots,values,result,'기호와 고친 표현')}</section>`;if(guide?.kind==='summary'||slots.length>1)return `<section class="written-workspace summary-slots">${writingGuideHtml(guide)}${writtenSlotsHtml(slots,values,result,'한 단어')}</section>`;return `<section class="written-workspace sentence">${writingGuideHtml(guide)}<label class="sentence-answer"><span>${esc(slots[0]?.label||'완성 문장')}</span><textarea rows="3" data-written-slot="0" placeholder="완성한 영어 문장을 입력하세요" ${result?'disabled':''} autocomplete="off" spellcheck="false">${esc(values[0]||'')}</textarea></label></section>`;}return `${result?'':'<p class="choice-swipe-hint">왼쪽으로 밀면 제외 · 오른쪽으로 밀면 정답 후보</p>'}<section class="question-answer-area" aria-label="선택지">${question.choices.map((choice,index)=>questionChoiceHtml(question,choice,index,result,selected.includes(index),choiceMarks[index])).join('')}</section>`;}
function hasResponse(question,selected,inlineSelected=[]){if(question.interaction==='inline_options')return inlineSelected.length===question.inlineGroups.length&&inlineSelected.every(Number.isInteger);return question.responseType==='written'?Array.isArray(selected)&&selected.length===(question.responseSlots?.length||1)&&selected.every(value=>String(value).trim()):Array.isArray(selected)&&selected.length>0;}
function resultFeedbackHtml(question,result){if(!result)return '';const explanation=String(result.explanation||'').trim(),action=explanation?`<div class="feedback-actions"><button type="button" data-toggle-explanation>${result.showExplanation?'해설 닫기':'해설 보기'}</button></div>`:'',revealed=result.showExplanation&&explanation?`<p class="explanation-reveal">${esc(explanation)}</p>`:'';if(result.correct)return `<div class="question-feedback correct"><strong>정답입니다.</strong><span>이 문제는 학습 목록에서 빠집니다.</span>${action}${revealed}</div>`;return `<div class="question-feedback wrong"><strong>오답으로 기록했습니다.</strong><span>정답은 선택지 색으로 표시되며 오답 복습에 자동으로 추가됩니다.</span>${action}${revealed}</div>`;}
function renderQuestion(){const session=state.questionSession;if(!session)return renderScope();const item=session.items[session.index],question=item.question||item,result=session.results[question.id],selected=session.responses[question.id]||[],inlineSelected=session.inlineSelections[question.id]||[],choiceMarks=session.choiceMarks[question.id]||[],phase=result?'submitted':'solving',displayPrompt=question.writingGuide?.title||question.prompt,explicit=question.renderSpec&&!question.renderSpec.legacyAdapter,extras=new Set(question.renderSpec?.extras||[]),showStimulus=question.stimulus&&(!explicit||extras.has('stimulus')),showSummary=question.summaryText&&(!explicit||extras.has('summary'));show('student-questions');$('#student-questions').innerHTML=`<button class="study-back" type="button" data-exit-questions aria-label="학습 목록으로"><span aria-hidden="true">‹</span></button><div class="question-layout" data-question-phase="${phase}"><div class="reader-shell"><div class="question-topline"><span class="question-progress">${question.source?.passageNo?`${question.source.passageNo}번 · `:''}${session.index+1} / ${session.items.length}</span></div><p class="eyebrow">PASSAGE · ${esc((question.renderer||question.family||'standard').toUpperCase())}</p>${showStimulus?`<section class="question-stimulus"><strong>주어진 문장</strong>${esc(question.stimulus)}</section>`:''}<article class="reading-passage question-passage">${questionPassageHtml(question,result,selected)}</article><h1 class="question-prompt">${esc(displayPrompt)}</h1>${showSummary?`<section class="question-summary">${esc(question.summaryText)}</section>`:''}${responseArea(question,result,selected,choiceMarks)}<div class="question-submit-row">${result?resultFeedbackHtml(question,result):`<button class="button primary question-submit" type="button" data-submit-question ${hasResponse(question,selected,inlineSelected)?'':'disabled'}>제출</button>`}</div><div class="question-nav"><button class="button quiet" type="button" data-question-prev ${session.index===0?'disabled':''}>← 이전</button><button class="button quiet" type="button" data-question-next>${session.index===session.items.length-1?'학습 목록':'다음 →'}</button></div></div></div>`;}
function startQuestionSession(items,mode='passage'){state.questionSession={items,index:0,responses:{},inlineSelections:{},choiceMarks:{},results:{},startedAt:performance.now(),mode};renderQuestion();}
async function openQuestions(passageId){if(!state.scope)return;const data=await safely(()=>call('student_questions',{examId:state.scope.id,passageId},state.token,'문제를 준비하는 중…'));if(!data)return;if(!data.questions?.length){toast('이 지문의 새 문제를 모두 풀었습니다.');return loadDashboard();}applyPassage(data);startQuestionSession(data.questions.map(question=>({...question,passageText:question.passageText||plainPassage()})));}
async function openReview(){if(!state.scope||!state.reviewCount)return;const data=await safely(()=>call('student_review_questions',{examId:state.scope.id},state.token,'복습 문제를 준비하는 중…'));if(!data)return;if(!data.items?.length){state.reviewCount=0;return renderScope();}startQuestionSession(data.items,'review');}
function selectInlineOption(groupIndex,optionIndex){const session=state.questionSession,item=session?.items[session.index],question=item?.question||item;if(!question||session.results[question.id]||question.interaction!=='inline_options')return;const current=[...(session.inlineSelections[question.id]||[])];current[groupIndex]=optionIndex;session.inlineSelections[question.id]=current;renderQuestion();}
function updateWrittenSlot(index,value){const session=state.questionSession,item=session?.items[session.index],question=item?.question||item;if(!question||session.results[question.id])return;const slots=question.responseSlots?.length||1,current=[...(session.responses[question.id]||Array(slots).fill(''))];current[index]=value;session.responses[question.id]=current;const submit=$('[data-submit-question]');if(submit)submit.disabled=!hasResponse(question,current);}
async function submitCurrentQuestion(){const session=state.questionSession,item=session?.items[session.index],question=item?.question||item,response=question?session.responses[question.id]||[]:[],inlineSelected=question?session.inlineSelections[question.id]||[]:[];if(!question||!hasResponse(question,response,inlineSelected)||session.results[question.id])return;const body={examId:state.scope.id,questionId:question.id,elapsedMs:Math.round(performance.now()-session.startedAt)};if(question.responseType==='written')body.responses=response;else if(question.interaction==='inline_options')body.inlineSelected=inlineSelected;else body.selected=response;const data=await safely(()=>call('submit_attempt',body,state.token,'답을 채점하는 중…'));if(!data)return;session.results[question.id]={correct:data.correct,answer:data.answer,explanation:data.explanation,showExplanation:false};renderQuestion();}
function toggleExplanation(){const session=state.questionSession,item=session?.items[session.index],question=item?.question||item,result=question&&session.results[question.id];if(!result||!result.explanation)return;result.showExplanation=!result.showExplanation;renderQuestion();}
function moveQuestion(delta){const session=state.questionSession;if(!session)return;const next=session.index+delta;if(next>=session.items.length){state.questionSession=null;return loadDashboard();}if(next<0)return;session.index=next;session.startedAt=performance.now();renderQuestion();}
function exitQuestions(){state.questionSession=null;return loadDashboard();}
async function logout(){if(state.token)record('logout');clearSession();await chooseStudent();}

// Selection state has one source of truth: a ruled-out choice can never remain
// in the response that is submitted.
function selectQuestionChoice(index){const session=state.questionSession,item=session?.items[session.index],question=item?.question||item;if(!question||session.results[question.id]||question.responseType==='written')return;const current=session.responses[question.id]||[],marks=[...(session.choiceMarks[question.id]||[])];marks[index]='neutral';session.choiceMarks[question.id]=marks;session.responses[question.id]=question.multiSelect?(current.includes(index)?current.filter(value=>value!==index):[...current,index].sort((a,b)=>a-b)):[index];renderQuestion();}
function markQuestionChoice(index,direction){const session=state.questionSession,item=session?.items[session.index],question=item?.question||item;if(!question||session.results[question.id]||question.responseType==='written')return;const marks=[...(session.choiceMarks[question.id]||[])],current=marks[index]||'neutral';marks[index]=direction==='left'?(current==='eliminated'?'neutral':'eliminated'):(current==='candidate'?'neutral':'candidate');session.choiceMarks[question.id]=marks;if(marks[index]==='eliminated')session.responses[question.id]=(session.responses[question.id]||[]).filter(value=>value!==index);renderQuestion();}

let choiceSwipe=null,choiceClickBlockedUntil=0;
function finishChoiceSwipe(event,cancelled=false){if(!choiceSwipe||event.pointerId!==choiceSwipe.pointerId)return;const swipe=choiceSwipe;choiceSwipe=null;swipe.node.classList.remove('swiping');swipe.node.style.removeProperty('--choice-drag');swipe.node.removeAttribute('data-swipe-direction');const dx=event.clientX-swipe.startX,dy=event.clientY-swipe.startY;if(!cancelled&&Math.abs(dx)>=46&&Math.abs(dx)>Math.abs(dy)){choiceClickBlockedUntil=Date.now()+450;markQuestionChoice(Number(swipe.node.dataset.questionChoice),dx<0?'left':'right');}}
document.addEventListener('pointerdown',event=>{const choice=event.target.closest?.('[data-question-choice]');if(!choice||event.button>0||choice.closest('[data-question-phase="submitted"]'))return;choiceSwipe={node:choice,pointerId:event.pointerId,startX:event.clientX,startY:event.clientY};choice.setPointerCapture?.(event.pointerId);choice.classList.add('swiping');});
document.addEventListener('pointermove',event=>{if(!choiceSwipe||event.pointerId!==choiceSwipe.pointerId)return;const dx=event.clientX-choiceSwipe.startX,dy=event.clientY-choiceSwipe.startY;if(Math.abs(dx)<=Math.abs(dy)||Math.abs(dx)<6)return;event.preventDefault();const distance=Math.max(-76,Math.min(76,dx));choiceSwipe.node.style.setProperty('--choice-drag',`${distance}px`);choiceSwipe.node.dataset.swipeDirection=distance<0?'left':'right';},{passive:false});
document.addEventListener('pointerup',event=>finishChoiceSwipe(event));
document.addEventListener('pointercancel',event=>finishChoiceSwipe(event,true));
document.addEventListener('click',event=>{const button=event.target.closest('button'),choice=event.target.closest('[data-question-choice]');if(choice){if(Date.now()<choiceClickBlockedUntil){event.preventDefault();return;}return selectQuestionChoice(Number(choice.dataset.questionChoice));}if(button?.dataset.workbookChoiceGroup!==undefined)return chooseWorkbookOption(Number(button.dataset.workbookChoiceGroup),button.dataset.workbookChoiceValue||'');if(button?.dataset.workbookOrderAdd){const [group,chip]=button.dataset.workbookOrderAdd.split(':').map(Number);return changeWorkbookOrder(group,chip);}if(button?.dataset.workbookOrderRemove){const [group,chip]=button.dataset.workbookOrderRemove.split(':').map(Number);return changeWorkbookOrder(group,chip,true);}if(button?.id==='theme-toggle')return theme(document.body.classList.contains('dark')?'light':'dark');if(button?.id==='logout')return logout();if(button?.dataset.studentId)return openPin({id:button.dataset.studentId,name:button.dataset.studentName});if(button?.hasAttribute('data-back-students'))return chooseStudent();if(button?.dataset.startWorkbook)return openWorkbook(button.dataset.startWorkbook);if(button?.dataset.startPassage)return openPassageStudy(button.dataset.startPassage);if(button?.dataset.startQuestions)return openQuestions(button.dataset.startQuestions);if(button?.hasAttribute('data-open-review')||button?.dataset.studentRoute==='review')return openReview();if(button?.hasAttribute('data-exit-workbook'))return renderScope();if(button?.hasAttribute('data-submit-workbook'))return submitWorkbook();if(button?.hasAttribute('data-workbook-retry'))return retryWorkbook();if(button?.hasAttribute('data-workbook-next'))return moveWorkbook(1);if(button?.hasAttribute('data-workbook-prev'))return moveWorkbook(-1);if(button?.dataset.workbookStage!==undefined)return setWorkbookStage(Number(button.dataset.workbookStage));if(button?.hasAttribute('data-exit-questions')||(button?.dataset.studentRoute==='passages'&&state.questionSession))return exitQuestions();if(button?.hasAttribute('data-exit-study')||button?.dataset.studentRoute==='passages')return renderScope();if(button?.hasAttribute('data-submit-question'))return submitCurrentQuestion();if(button?.hasAttribute('data-toggle-explanation'))return toggleExplanation();if(button?.hasAttribute('data-question-prev'))return moveQuestion(-1);if(button?.hasAttribute('data-question-next'))return moveQuestion(1);});
document.addEventListener('input',event=>{if(event.target.matches('[data-written-slot]'))updateWrittenSlot(Number(event.target.dataset.writtenSlot),event.target.value);if(event.target.matches('[data-workbook-slot]'))updateWorkbookSlot(Number(event.target.dataset.workbookSlot),event.target.value);});
document.addEventListener('keydown',event=>{if(event.key!=='Enter'||!state.workbookSession||$('#student-workbook').hidden||event.target.matches('textarea'))return;const {session,item}=workbookCurrent(),result=session?.results?.[item?.key];if(!result&&!event.target.matches('[data-workbook-slot],[data-submit-workbook]'))return;event.preventDefault();if(!result)return submitWorkbook();if(result.correct)return moveWorkbook(1);return retryWorkbook();});
document.addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='pin-form')return login(event.target);});
document.addEventListener('keydown',event=>{const choice=event.target.closest?.('[data-question-choice]');if(choice&&(event.key==='Enter'||event.key===' ')){event.preventDefault();selectQuestionChoice(Number(choice.dataset.questionChoice));}});

theme(localStorage.getItem('ready-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));
try{const previous=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(previous?.token){state.token=previous.token;loadDashboard();}else chooseStudent();}catch{chooseStudent();}
